// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/mmdeviceapi.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System.Runtime.Versioning;

namespace Silk.NET.Windows;
/// <include file='AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.xml' path='doc/member[@name="AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE"]/*'/>
[SupportedOSPlatform("windows10.0.22621.0")]
public enum AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE
{
    /// <include file='AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.xml' path='doc/member[@name="AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_DEFAULT"]/*'/>
    AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_DEFAULT = 0,
    /// <include file='AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.xml' path='doc/member[@name="AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_USER"]/*'/>
    AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_USER = 1,
    /// <include file='AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.xml' path='doc/member[@name="AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_VOLATILE"]/*'/>
    AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_VOLATILE = 2,
    /// <include file='AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.xml' path='doc/member[@name="AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_ENUM_COUNT"]/*'/>
    AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_ENUM_COUNT = (AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE_VOLATILE + 1),
}