// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/WebServices.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace Silk.NET.Windows;
/// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID"]/*'/>
public enum WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID
{
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_APPLIES_TO"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_APPLIES_TO = 1,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_TRUST_VERSION"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_TRUST_VERSION = 2,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_SECURE_CONVERSATION_VERSION"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_SECURE_CONVERSATION_VERSION = 3,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_TYPE"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_TYPE = 4,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_REQUEST_ACTION"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_REQUEST_ACTION = 5,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_EXISTING_TOKEN"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_EXISTING_TOKEN = 6,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_TYPE"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_TYPE = 7,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_SIZE"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_SIZE = 8,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_ENTROPY"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_ISSUED_TOKEN_KEY_ENTROPY = 9,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_LOCAL_REQUEST_PARAMETERS"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_LOCAL_REQUEST_PARAMETERS = 10,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_SERVICE_REQUEST_PARAMETERS"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_SERVICE_REQUEST_PARAMETERS = 11,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_MESSAGE_PROPERTIES"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_MESSAGE_PROPERTIES = 12,
    /// <include file='WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.xml' path='doc/member[@name="WS_REQUEST_SECURITY_TOKEN_PROPERTY_ID.WS_REQUEST_SECURITY_TOKEN_PROPERTY_BEARER_KEY_TYPE_VERSION"]/*'/>
    WS_REQUEST_SECURITY_TOKEN_PROPERTY_BEARER_KEY_TYPE_VERSION = 13,
}