// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/WebServices.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.Windows;
/// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID"]/*'/>
public enum WS_XML_WRITER_PROPERTY_ID
{
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_MAX_DEPTH"]/*'/>
    WS_XML_WRITER_PROPERTY_MAX_DEPTH = 0,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_ALLOW_FRAGMENT"]/*'/>
    WS_XML_WRITER_PROPERTY_ALLOW_FRAGMENT = 1,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_MAX_ATTRIBUTES"]/*'/>
    WS_XML_WRITER_PROPERTY_MAX_ATTRIBUTES = 2,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_WRITE_DECLARATION"]/*'/>
    WS_XML_WRITER_PROPERTY_WRITE_DECLARATION = 3,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_INDENT"]/*'/>
    WS_XML_WRITER_PROPERTY_INDENT = 4,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_BUFFER_TRIM_SIZE"]/*'/>
    WS_XML_WRITER_PROPERTY_BUFFER_TRIM_SIZE = 5,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_CHARSET"]/*'/>
    WS_XML_WRITER_PROPERTY_CHARSET = 6,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_BUFFERS"]/*'/>
    WS_XML_WRITER_PROPERTY_BUFFERS = 7,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_BUFFER_MAX_SIZE"]/*'/>
    WS_XML_WRITER_PROPERTY_BUFFER_MAX_SIZE = 8,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_BYTES"]/*'/>
    WS_XML_WRITER_PROPERTY_BYTES = 9,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_IN_ATTRIBUTE"]/*'/>
    WS_XML_WRITER_PROPERTY_IN_ATTRIBUTE = 10,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_MAX_MIME_PARTS_BUFFER_SIZE"]/*'/>
    WS_XML_WRITER_PROPERTY_MAX_MIME_PARTS_BUFFER_SIZE = 11,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_INITIAL_BUFFER"]/*'/>
    WS_XML_WRITER_PROPERTY_INITIAL_BUFFER = 12,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_ALLOW_INVALID_CHARACTER_REFERENCES"]/*'/>
    WS_XML_WRITER_PROPERTY_ALLOW_INVALID_CHARACTER_REFERENCES = 13,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_MAX_NAMESPACES"]/*'/>
    WS_XML_WRITER_PROPERTY_MAX_NAMESPACES = 14,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_BYTES_WRITTEN"]/*'/>
    WS_XML_WRITER_PROPERTY_BYTES_WRITTEN = 15,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_BYTES_TO_CLOSE"]/*'/>
    WS_XML_WRITER_PROPERTY_BYTES_TO_CLOSE = 16,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_COMPRESS_EMPTY_ELEMENTS"]/*'/>
    WS_XML_WRITER_PROPERTY_COMPRESS_EMPTY_ELEMENTS = 17,
    /// <include file='WS_XML_WRITER_PROPERTY_ID.xml' path='doc/member[@name="WS_XML_WRITER_PROPERTY_ID.WS_XML_WRITER_PROPERTY_EMIT_UNCOMPRESSED_EMPTY_ELEMENTS"]/*'/>
    WS_XML_WRITER_PROPERTY_EMIT_UNCOMPRESSED_EMPTY_ELEMENTS = 18,
}