// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/d2d1effects.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace Silk.NET.DirectX;
/// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP"]/*'/>
public enum D2D1_GAMMATRANSFER_PROP
{
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_RED_AMPLITUDE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_RED_AMPLITUDE = 0,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_RED_EXPONENT"]/*'/>
    D2D1_GAMMATRANSFER_PROP_RED_EXPONENT = 1,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_RED_OFFSET"]/*'/>
    D2D1_GAMMATRANSFER_PROP_RED_OFFSET = 2,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_RED_DISABLE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_RED_DISABLE = 3,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_GREEN_AMPLITUDE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_GREEN_AMPLITUDE = 4,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_GREEN_EXPONENT"]/*'/>
    D2D1_GAMMATRANSFER_PROP_GREEN_EXPONENT = 5,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_GREEN_OFFSET"]/*'/>
    D2D1_GAMMATRANSFER_PROP_GREEN_OFFSET = 6,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_GREEN_DISABLE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_GREEN_DISABLE = 7,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_BLUE_AMPLITUDE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_BLUE_AMPLITUDE = 8,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_BLUE_EXPONENT"]/*'/>
    D2D1_GAMMATRANSFER_PROP_BLUE_EXPONENT = 9,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_BLUE_OFFSET"]/*'/>
    D2D1_GAMMATRANSFER_PROP_BLUE_OFFSET = 10,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_BLUE_DISABLE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_BLUE_DISABLE = 11,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_ALPHA_AMPLITUDE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_ALPHA_AMPLITUDE = 12,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_ALPHA_EXPONENT"]/*'/>
    D2D1_GAMMATRANSFER_PROP_ALPHA_EXPONENT = 13,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_ALPHA_OFFSET"]/*'/>
    D2D1_GAMMATRANSFER_PROP_ALPHA_OFFSET = 14,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_ALPHA_DISABLE"]/*'/>
    D2D1_GAMMATRANSFER_PROP_ALPHA_DISABLE = 15,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_CLAMP_OUTPUT"]/*'/>
    D2D1_GAMMATRANSFER_PROP_CLAMP_OUTPUT = 16,
    /// <include file='D2D1_GAMMATRANSFER_PROP.xml' path='doc/member[@name="D2D1_GAMMATRANSFER_PROP.D2D1_GAMMATRANSFER_PROP_FORCE_DWORD"]/*'/>
    D2D1_GAMMATRANSFER_PROP_FORCE_DWORD = unchecked((int)(0xffffffff)),
}