// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/d3d11sdklayers.h in the Windows SDK for Windows 10.0.26100.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;
using System.Runtime.Versioning;
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

[Flags]
[SupportedOSPlatform("windows6.2")]
public enum D3D11_SHADER_TRACKING_OPTIONS
{
    D3D11_SHADER_TRACKING_OPTION_IGNORE = 0,
    D3D11_SHADER_TRACKING_OPTION_TRACK_UNINITIALIZED = 0x1,
    D3D11_SHADER_TRACKING_OPTION_TRACK_RAW = 0x2,
    D3D11_SHADER_TRACKING_OPTION_TRACK_WAR = 0x4,
    D3D11_SHADER_TRACKING_OPTION_TRACK_WAW = 0x8,
    D3D11_SHADER_TRACKING_OPTION_ALLOW_SAME = 0x10,
    D3D11_SHADER_TRACKING_OPTION_TRACK_ATOMIC_CONSISTENCY = 0x20,
    D3D11_SHADER_TRACKING_OPTION_TRACK_RAW_ACROSS_THREADGROUPS = 0x40,
    D3D11_SHADER_TRACKING_OPTION_TRACK_WAR_ACROSS_THREADGROUPS = 0x80,
    D3D11_SHADER_TRACKING_OPTION_TRACK_WAW_ACROSS_THREADGROUPS = 0x100,
    D3D11_SHADER_TRACKING_OPTION_TRACK_ATOMIC_CONSISTENCY_ACROSS_THREADGROUPS = 0x200,
    D3D11_SHADER_TRACKING_OPTION_UAV_SPECIFIC_FLAGS =
        (
            (
                (
                    D3D11_SHADER_TRACKING_OPTION_TRACK_RAW_ACROSS_THREADGROUPS
                    | D3D11_SHADER_TRACKING_OPTION_TRACK_WAR_ACROSS_THREADGROUPS
                ) | D3D11_SHADER_TRACKING_OPTION_TRACK_WAW_ACROSS_THREADGROUPS
            ) | D3D11_SHADER_TRACKING_OPTION_TRACK_ATOMIC_CONSISTENCY_ACROSS_THREADGROUPS
        ),
    D3D11_SHADER_TRACKING_OPTION_ALL_HAZARDS =
        (
            (
                (
                    (
                        (
                            (
                                (
                                    D3D11_SHADER_TRACKING_OPTION_TRACK_RAW
                                    | D3D11_SHADER_TRACKING_OPTION_TRACK_WAR
                                ) | D3D11_SHADER_TRACKING_OPTION_TRACK_WAW
                            ) | D3D11_SHADER_TRACKING_OPTION_TRACK_ATOMIC_CONSISTENCY
                        ) | D3D11_SHADER_TRACKING_OPTION_TRACK_RAW_ACROSS_THREADGROUPS
                    ) | D3D11_SHADER_TRACKING_OPTION_TRACK_WAR_ACROSS_THREADGROUPS
                ) | D3D11_SHADER_TRACKING_OPTION_TRACK_WAW_ACROSS_THREADGROUPS
            ) | D3D11_SHADER_TRACKING_OPTION_TRACK_ATOMIC_CONSISTENCY_ACROSS_THREADGROUPS
        ),
    D3D11_SHADER_TRACKING_OPTION_ALL_HAZARDS_ALLOWING_SAME =
        (D3D11_SHADER_TRACKING_OPTION_ALL_HAZARDS | D3D11_SHADER_TRACKING_OPTION_ALLOW_SAME),
    D3D11_SHADER_TRACKING_OPTION_ALL_OPTIONS =
        (
            D3D11_SHADER_TRACKING_OPTION_ALL_HAZARDS_ALLOWING_SAME
            | D3D11_SHADER_TRACKING_OPTION_TRACK_UNINITIALIZED
        ),
}
