// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/DocObj.h in the Windows SDK for Windows 10.0.26100.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.Windows;

[Flags]
public enum OLECMDID_REFRESHFLAG
{
    OLECMDIDF_REFRESH_NORMAL = 0,
    OLECMDIDF_REFRESH_IFEXPIRED = 1,
    OLECMDIDF_REFRESH_CONTINUE = 2,
    OLECMDIDF_REFRESH_COMPLETELY = 3,
    OLECMDIDF_REFRESH_NO_CACHE = 4,
    OLECMDIDF_REFRESH_RELOAD = 5,
    OLECMDIDF_REFRESH_LEVELMASK = 0x00FF,
    OLECMDIDF_REFRESH_CLEARUSERINPUT = 0x1000,
    OLECMDIDF_REFRESH_PROMPTIFOFFLINE = 0x2000,
    OLECMDIDF_REFRESH_THROUGHSCRIPT = 0x4000,
    OLECMDIDF_REFRESH_SKIPBEFOREUNLOADEVENT = 0x8000,
    OLECMDIDF_REFRESH_PAGEACTION_ACTIVEXINSTALL = 0x00010000,
    OLECMDIDF_REFRESH_PAGEACTION_FILEDOWNLOAD = 0x00020000,
    OLECMDIDF_REFRESH_PAGEACTION_LOCALMACHINE = 0x00040000,
    OLECMDIDF_REFRESH_PAGEACTION_POPUPWINDOW = 0x00080000,
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNLOCALMACHINE = 0x00100000,
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNTRUSTED = 0x00200000,
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTRANET = 0x00400000,
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTERNET = 0x00800000,
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNRESTRICTED = 0x01000000,
    OLECMDIDF_REFRESH_PAGEACTION_MIXEDCONTENT = 0x02000000,
    OLECMDIDF_REFRESH_PAGEACTION_INVALID_CERT = 0x04000000,
    OLECMDIDF_REFRESH_PAGEACTION_ALLOW_VERSION = 0x08000000,
}
