// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/Msi.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.

using static Silk.NET.Windows.INSTALLMESSAGE;

namespace Silk.NET.Windows;

/// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE"]/*' />
public enum INSTALLLOGMODE
{
    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_FATALEXIT"]/*' />
    INSTALLLOGMODE_FATALEXIT = (1 << (INSTALLMESSAGE_FATALEXIT >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_ERROR"]/*' />
    INSTALLLOGMODE_ERROR = (1 << (INSTALLMESSAGE_ERROR >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_WARNING"]/*' />
    INSTALLLOGMODE_WARNING = (1 << (INSTALLMESSAGE_WARNING >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_USER"]/*' />
    INSTALLLOGMODE_USER = (1 << (INSTALLMESSAGE_USER >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_INFO"]/*' />
    INSTALLLOGMODE_INFO = (1 << (INSTALLMESSAGE_INFO >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_RESOLVESOURCE"]/*' />
    INSTALLLOGMODE_RESOLVESOURCE = (1 << (INSTALLMESSAGE_RESOLVESOURCE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_OUTOFDISKSPACE"]/*' />
    INSTALLLOGMODE_OUTOFDISKSPACE = (1 << (INSTALLMESSAGE_OUTOFDISKSPACE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_ACTIONSTART"]/*' />
    INSTALLLOGMODE_ACTIONSTART = (1 << (INSTALLMESSAGE_ACTIONSTART >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_ACTIONDATA"]/*' />
    INSTALLLOGMODE_ACTIONDATA = (1 << (INSTALLMESSAGE_ACTIONDATA >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_COMMONDATA"]/*' />
    INSTALLLOGMODE_COMMONDATA = (1 << (INSTALLMESSAGE_COMMONDATA >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_PROPERTYDUMP"]/*' />
    INSTALLLOGMODE_PROPERTYDUMP = (1 << (INSTALLMESSAGE_PROGRESS >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_VERBOSE"]/*' />
    INSTALLLOGMODE_VERBOSE = (1 << (INSTALLMESSAGE_INITIALIZE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_EXTRADEBUG"]/*' />
    INSTALLLOGMODE_EXTRADEBUG = (1 << (INSTALLMESSAGE_TERMINATE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_LOGONLYONERROR"]/*' />
    INSTALLLOGMODE_LOGONLYONERROR = (1 << (INSTALLMESSAGE_SHOWDIALOG >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_LOGPERFORMANCE"]/*' />
    INSTALLLOGMODE_LOGPERFORMANCE = (1 << (INSTALLMESSAGE_PERFORMANCE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_PROGRESS"]/*' />
    INSTALLLOGMODE_PROGRESS = (1 << (INSTALLMESSAGE_PROGRESS >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_INITIALIZE"]/*' />
    INSTALLLOGMODE_INITIALIZE = (1 << (INSTALLMESSAGE_INITIALIZE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_TERMINATE"]/*' />
    INSTALLLOGMODE_TERMINATE = (1 << (INSTALLMESSAGE_TERMINATE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_SHOWDIALOG"]/*' />
    INSTALLLOGMODE_SHOWDIALOG = (1 << (INSTALLMESSAGE_SHOWDIALOG >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_FILESINUSE"]/*' />
    INSTALLLOGMODE_FILESINUSE = (1 << (INSTALLMESSAGE_FILESINUSE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_RMFILESINUSE"]/*' />
    INSTALLLOGMODE_RMFILESINUSE = (1 << (INSTALLMESSAGE_RMFILESINUSE >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_INSTALLSTART"]/*' />
    INSTALLLOGMODE_INSTALLSTART = (1 << (INSTALLMESSAGE_INSTALLSTART >> 24)),

    /// <include file='INSTALLLOGMODE.xml' path='doc/member[@name="INSTALLLOGMODE.INSTALLLOGMODE_INSTALLEND"]/*' />
    INSTALLLOGMODE_INSTALLEND = (1 << (INSTALLMESSAGE_INSTALLEND >> 24)),
}
