version: 2
updates:
- package-ecosystem: nuget
  target-branch: main
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
  groups:
    silk2_deps:
      patterns:
        - "*"
- package-ecosystem: nuget
  target-branch: develop/3.0
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
  groups:
    silk3_deps:
      patterns:
        - "*"
