// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/dwrite_1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace Silk.NET.DirectX;

/// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS"]/*' />
public enum DWRITE_PANOSE_DECORATIVE_CLASS
{
    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_ANY"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_ANY = 0,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_NO_FIT"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_NO_FIT = 1,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_DERIVATIVE"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_DERIVATIVE = 2,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_NONSTANDARD_TOPOLOGY"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_NONSTANDARD_TOPOLOGY = 3,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_NONSTANDARD_ELEMENTS"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_NONSTANDARD_ELEMENTS = 4,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_NONSTANDARD_ASPECT"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_NONSTANDARD_ASPECT = 5,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_INITIALS"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_INITIALS = 6,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_CARTOON"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_CARTOON = 7,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_PICTURE_STEMS"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_PICTURE_STEMS = 8,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_ORNAMENTED"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_ORNAMENTED = 9,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_TEXT_AND_BACKGROUND"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_TEXT_AND_BACKGROUND = 10,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_COLLAGE"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_COLLAGE = 11,

    /// <include file='DWRITE_PANOSE_DECORATIVE_CLASS.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_CLASS.DWRITE_PANOSE_DECORATIVE_CLASS_MONTAGE"]/*' />
    DWRITE_PANOSE_DECORATIVE_CLASS_MONTAGE = 12,
}
