// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/dwrite_1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.DirectX;
/// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE"]/*'/>
public enum DWRITE_PANOSE_SERIF_STYLE
{
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_ANY"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_ANY = 0,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_NO_FIT"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_NO_FIT = 1,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_COVE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_COVE = 2,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_OBTUSE_COVE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_OBTUSE_COVE = 3,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_SQUARE_COVE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_SQUARE_COVE = 4,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_OBTUSE_SQUARE_COVE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_OBTUSE_SQUARE_COVE = 5,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_SQUARE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_SQUARE = 6,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_THIN"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_THIN = 7,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_OVAL"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_OVAL = 8,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_EXAGGERATED"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_EXAGGERATED = 9,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_TRIANGLE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_TRIANGLE = 10,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_NORMAL_SANS"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_NORMAL_SANS = 11,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_OBTUSE_SANS"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_OBTUSE_SANS = 12,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_PERPENDICULAR_SANS"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_PERPENDICULAR_SANS = 13,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_FLARED"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_FLARED = 14,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_ROUNDED"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_ROUNDED = 15,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_SCRIPT"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_SCRIPT = 16,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_PERP_SANS"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_PERP_SANS = DWRITE_PANOSE_SERIF_STYLE_PERPENDICULAR_SANS,
    /// <include file='DWRITE_PANOSE_SERIF_STYLE.xml' path='doc/member[@name="DWRITE_PANOSE_SERIF_STYLE.DWRITE_PANOSE_SERIF_STYLE_BONE"]/*'/>
    DWRITE_PANOSE_SERIF_STYLE_BONE = DWRITE_PANOSE_SERIF_STYLE_OVAL,
}