// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/dwrite_1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace Silk.NET.DirectX;
/// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION"]/*'/>
public enum DWRITE_PANOSE_STROKE_VARIATION
{
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_ANY"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_ANY = 0,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_NO_FIT"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_NO_FIT = 1,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_NO_VARIATION"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_NO_VARIATION = 2,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_DIAGONAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_DIAGONAL = 3,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_TRANSITIONAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_TRANSITIONAL = 4,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_VERTICAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_VERTICAL = 5,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_HORIZONTAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_GRADUAL_HORIZONTAL = 6,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_RAPID_VERTICAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_RAPID_VERTICAL = 7,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_RAPID_HORIZONTAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_RAPID_HORIZONTAL = 8,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_INSTANT_VERTICAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_INSTANT_VERTICAL = 9,
    /// <include file='DWRITE_PANOSE_STROKE_VARIATION.xml' path='doc/member[@name="DWRITE_PANOSE_STROKE_VARIATION.DWRITE_PANOSE_STROKE_VARIATION_INSTANT_HORIZONTAL"]/*'/>
    DWRITE_PANOSE_STROKE_VARIATION_INSTANT_HORIZONTAL = 10,
}