// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/dwrite_1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.DirectX;
/// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY"]/*'/>
public enum DWRITE_PANOSE_SCRIPT_TOPOLOGY
{
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_ANY"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_ANY = 0,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_NO_FIT"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_NO_FIT = 1,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_ROMAN_DISCONNECTED"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_ROMAN_DISCONNECTED = 2,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_ROMAN_TRAILING"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_ROMAN_TRAILING = 3,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_ROMAN_CONNECTED"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_ROMAN_CONNECTED = 4,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_CURSIVE_DISCONNECTED"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_CURSIVE_DISCONNECTED = 5,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_CURSIVE_TRAILING"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_CURSIVE_TRAILING = 6,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_CURSIVE_CONNECTED"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_CURSIVE_CONNECTED = 7,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_BLACKLETTER_DISCONNECTED"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_BLACKLETTER_DISCONNECTED = 8,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_BLACKLETTER_TRAILING"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_BLACKLETTER_TRAILING = 9,
    /// <include file='DWRITE_PANOSE_SCRIPT_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_SCRIPT_TOPOLOGY.DWRITE_PANOSE_SCRIPT_TOPOLOGY_BLACKLETTER_CONNECTED"]/*'/>
    DWRITE_PANOSE_SCRIPT_TOPOLOGY_BLACKLETTER_CONNECTED = 10,
}