// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/dwrite_1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.DirectX;
/// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY"]/*'/>
public enum DWRITE_PANOSE_DECORATIVE_TOPOLOGY
{
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_ANY"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_ANY = 0,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_NO_FIT"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_NO_FIT = 1,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_STANDARD"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_STANDARD = 2,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_SQUARE"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_SQUARE = 3,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_MULTIPLE_SEGMENT"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_MULTIPLE_SEGMENT = 4,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_ART_DECO"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_ART_DECO = 5,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_UNEVEN_WEIGHTING"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_UNEVEN_WEIGHTING = 6,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_DIVERSE_ARMS"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_DIVERSE_ARMS = 7,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_DIVERSE_FORMS"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_DIVERSE_FORMS = 8,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_LOMBARDIC_FORMS"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_LOMBARDIC_FORMS = 9,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_UPPER_CASE_IN_LOWER_CASE"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_UPPER_CASE_IN_LOWER_CASE = 10,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_IMPLIED_TOPOLOGY"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_IMPLIED_TOPOLOGY = 11,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_HORSESHOE_E_AND_A"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_HORSESHOE_E_AND_A = 12,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_CURSIVE"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_CURSIVE = 13,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_BLACKLETTER"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_BLACKLETTER = 14,
    /// <include file='DWRITE_PANOSE_DECORATIVE_TOPOLOGY.xml' path='doc/member[@name="DWRITE_PANOSE_DECORATIVE_TOPOLOGY.DWRITE_PANOSE_DECORATIVE_TOPOLOGY_SWASH_VARIANCE"]/*'/>
    DWRITE_PANOSE_DECORATIVE_TOPOLOGY_SWASH_VARIANCE = 15,
}