// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/dwrite_1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace Silk.NET.DirectX;

/// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM"]/*' />
public enum DWRITE_PANOSE_LETTERFORM
{
    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_ANY"]/*' />
    DWRITE_PANOSE_LETTERFORM_ANY = 0,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NO_FIT"]/*' />
    DWRITE_PANOSE_LETTERFORM_NO_FIT = 1,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_CONTACT"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_CONTACT = 2,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_WEIGHTED"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_WEIGHTED = 3,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_BOXED"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_BOXED = 4,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_FLATTENED"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_FLATTENED = 5,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_ROUNDED"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_ROUNDED = 6,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_OFF_CENTER"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_OFF_CENTER = 7,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_NORMAL_SQUARE"]/*' />
    DWRITE_PANOSE_LETTERFORM_NORMAL_SQUARE = 8,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_CONTACT"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_CONTACT = 9,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_WEIGHTED"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_WEIGHTED = 10,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_BOXED"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_BOXED = 11,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_FLATTENED"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_FLATTENED = 12,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_ROUNDED"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_ROUNDED = 13,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_OFF_CENTER"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_OFF_CENTER = 14,

    /// <include file='DWRITE_PANOSE_LETTERFORM.xml' path='doc/member[@name="DWRITE_PANOSE_LETTERFORM.DWRITE_PANOSE_LETTERFORM_OBLIQUE_SQUARE"]/*' />
    DWRITE_PANOSE_LETTERFORM_OBLIQUE_SQUARE = 15,
}
