<Project>
  <ItemGroup>
    <!-- Common -->
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.2" />
    <PackageVersion Include="DotNet.ReproducibleBuilds.Isolated" Version="2.0.2" />
    <PackageVersion Include="Microsoft.Build.Tasks.Core" Version="17.14.28" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="NAudio.Core" Version="2.3.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.14.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <!-- eng/benchmarks -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <!-- Silk.NET.Core -->
    <PackageVersion Include="Fody" Version="6.9.3" PrivateAssets="all" />
    <PackageVersion Include="InlineIL.Fody" Version="1.10.2" PrivateAssets="all" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.0.0-1.25277.114" />
    <!-- Analyzers -->
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" />
    <!-- SilkTouch -->
    <PackageVersion Include="ClangSharp.PInvokeGenerator" Version="21.1.8.3" />
    <PackageVersion Include="CSharpier.Core" Version="1.3.0" />
    <PackageVersion Include="Humanizer.Core" Version="2.14.1" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.11.2" />
    <PackageVersion Include="Microsoft.Build.Framework" Version="18.7.1" />
    <PackageVersion Include="Microsoft.NET.StringTools" Version="18.7.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
    <PackageVersion Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="3.14.2075" />
    <PackageVersion Include="System.CommandLine" Version="2.0.9" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.9" />
    <!-- SilkTouch Unit Tests -->
    <PackageVersion Include="Silk.NET.BuildTools" Version="2.23.0-pr2526.5226" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.2.0" />
    <PackageVersion Include="Verify.NUnit" Version="31.19.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.3" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.8.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyModel" Version="10.0.9" />
  </ItemGroup>
</Project>
