// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// Ported from the OpenGL headers and corresponding dependencies.
// Original source is Copyright 2013-2020 The Khronos Group Inc. Licensed under the MIT license.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Silk.NET.OpenGL;

[Transformed]
public enum GetTextureParameter : uint
{
    TextureWidth = unchecked((uint)0x1000),
    TextureHeight = unchecked((uint)0x1001),
    TextureBorderColor = unchecked((uint)0x1004),
    TextureMagFilter = unchecked((uint)0x2800),
    TextureMinFilter = unchecked((uint)0x2801),
    TextureWrapS = unchecked((uint)0x2802),
    TextureWrapT = unchecked((uint)0x2803),
    TextureComponents = unchecked((uint)0x1003),
    TextureBorder = unchecked((uint)0x1005),
    TextureInternalFormat = unchecked((uint)0x1003),
    TextureRedSize = unchecked((uint)0x805C),
    TextureGreenSize = unchecked((uint)0x805D),
    TextureBlueSize = unchecked((uint)0x805E),
    TextureAlphaSize = unchecked((uint)0x805F),
    TextureLuminanceSize = unchecked((uint)0x8060),
    TextureIntensitySize = unchecked((uint)0x8061),
    TexturePriority = unchecked((uint)0x8066),
    TextureResident = unchecked((uint)0x8067),
    NormalMap = unchecked((uint)0x8511),
    ReflectionMap = unchecked((uint)0x8512),
    NormalMapARB = unchecked((uint)0x8511),
    ReflectionMapARB = unchecked((uint)0x8512),
    TextureDepthEXT = unchecked((uint)0x8071),
    TextureWrapREXT = unchecked((uint)0x8072),
    NormalMapEXT = unchecked((uint)0x8511),
    ReflectionMapEXT = unchecked((uint)0x8512),
    NormalMapNV = unchecked((uint)0x8511),
    ReflectionMapNV = unchecked((uint)0x8512),
    DetailTextureLevelSGIS = unchecked((uint)0x809A),
    DetailTextureModeSGIS = unchecked((uint)0x809B),
    DetailTextureFuncPointsSGIS = unchecked((uint)0x809C),
    GenerateMipmapSGIS = unchecked((uint)0x8191),
    SharpenTextureFuncPointsSGIS = unchecked((uint)0x80B0),
    Texture4DsizeSGIS = unchecked((uint)0x8136),
    TextureWrapQSGIS = unchecked((uint)0x8137),
    TextureFilter4SizeSGIS = unchecked((uint)0x8147),
    TextureMinLodSGIS = unchecked((uint)0x813A),
    TextureMaxLodSGIS = unchecked((uint)0x813B),
    TextureBaseLevelSGIS = unchecked((uint)0x813C),
    TextureMaxLevelSGIS = unchecked((uint)0x813D),
    DualTextureSelectSGIS = unchecked((uint)0x8124),
    QuadTextureSelectSGIS = unchecked((uint)0x8125),
    TextureClipmapCenterSGIX = unchecked((uint)0x8171),
    TextureClipmapFrameSGIX = unchecked((uint)0x8172),
    TextureClipmapOffsetSGIX = unchecked((uint)0x8173),
    TextureClipmapVirtualDepthSGIX = unchecked((uint)0x8174),
    TextureClipmapLodOffsetSGIX = unchecked((uint)0x8175),
    TextureClipmapDepthSGIX = unchecked((uint)0x8176),
    TextureCompareSGIX = unchecked((uint)0x819A),
    TextureCompareOperatorSGIX = unchecked((uint)0x819B),
    TextureLequalRSGIX = unchecked((uint)0x819C),
    TextureGequalRSGIX = unchecked((uint)0x819D),
    ShadowAmbientSGIX = unchecked((uint)0x80BF),
    TextureMaxClampSSGIX = unchecked((uint)0x8369),
    TextureMaxClampTSGIX = unchecked((uint)0x836A),
    TextureMaxClampRSGIX = unchecked((uint)0x836B),
    TextureLodBiasSSGIX = unchecked((uint)0x818E),
    TextureLodBiasTSGIX = unchecked((uint)0x818F),
    TextureLodBiasRSGIX = unchecked((uint)0x8190),
    PostTextureFilterBiasSGIX = unchecked((uint)0x8179),
    PostTextureFilterScaleSGIX = unchecked((uint)0x817A),
    TextureUnnormalizedCoordinatesARM = unchecked((uint)0x8F6A),
    SurfaceCompressionEXT = unchecked((uint)0x96C0),
    TextureBorderColorNV = unchecked((uint)0x1004),
    NormalMapOES = unchecked((uint)0x8511),
    ReflectionMapOES = unchecked((uint)0x8512),
}
