// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// Ported from the OpenGL headers and corresponding dependencies.
// Original source is Copyright 2013-2020 The Khronos Group Inc. Licensed under the MIT license.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Silk.NET.OpenGL;

[Transformed]
public enum InternalFormatPName : uint
{
    Samples = unchecked((uint)0x80A9),
    TextureCompressed = unchecked((uint)0x86A1),
    GenerateMipmap = unchecked((uint)0x8191),
    NumSampleCounts = unchecked((uint)0x9380),
    ImageFormatCompatibilityType = unchecked((uint)0x90C7),
    InternalformatSupported = unchecked((uint)0x826F),
    InternalformatPreferred = unchecked((uint)0x8270),
    InternalformatRedSize = unchecked((uint)0x8271),
    InternalformatGreenSize = unchecked((uint)0x8272),
    InternalformatBlueSize = unchecked((uint)0x8273),
    InternalformatAlphaSize = unchecked((uint)0x8274),
    InternalformatDepthSize = unchecked((uint)0x8275),
    InternalformatStencilSize = unchecked((uint)0x8276),
    InternalformatSharedSize = unchecked((uint)0x8277),
    InternalformatRedType = unchecked((uint)0x8278),
    InternalformatGreenType = unchecked((uint)0x8279),
    InternalformatBlueType = unchecked((uint)0x827A),
    InternalformatAlphaType = unchecked((uint)0x827B),
    InternalformatDepthType = unchecked((uint)0x827C),
    InternalformatStencilType = unchecked((uint)0x827D),
    MaxWidth = unchecked((uint)0x827E),
    MaxHeight = unchecked((uint)0x827F),
    MaxDepth = unchecked((uint)0x8280),
    MaxLayers = unchecked((uint)0x8281),
    ColorComponents = unchecked((uint)0x8283),
    ColorRenderable = unchecked((uint)0x8286),
    DepthRenderable = unchecked((uint)0x8287),
    StencilRenderable = unchecked((uint)0x8288),
    FramebufferRenderable = unchecked((uint)0x8289),
    FramebufferRenderableLayered = unchecked((uint)0x828A),
    FramebufferBlend = unchecked((uint)0x828B),
    ReadPixels = unchecked((uint)0x828C),
    ReadPixelsFormat = unchecked((uint)0x828D),
    ReadPixelsType = unchecked((uint)0x828E),
    TextureImageFormat = unchecked((uint)0x828F),
    TextureImageType = unchecked((uint)0x8290),
    GetTextureImageFormat = unchecked((uint)0x8291),
    GetTextureImageType = unchecked((uint)0x8292),
    Mipmap = unchecked((uint)0x8293),
    AutoGenerateMipmap = unchecked((uint)0x8295),
    ColorEncoding = unchecked((uint)0x8296),
    SrgbRead = unchecked((uint)0x8297),
    SrgbWrite = unchecked((uint)0x8298),
    Filter = unchecked((uint)0x829A),
    VertexTexture = unchecked((uint)0x829B),
    TessControlTexture = unchecked((uint)0x829C),
    TessEvaluationTexture = unchecked((uint)0x829D),
    GeometryTexture = unchecked((uint)0x829E),
    FragmentTexture = unchecked((uint)0x829F),
    ComputeTexture = unchecked((uint)0x82A0),
    TextureShadow = unchecked((uint)0x82A1),
    TextureGather = unchecked((uint)0x82A2),
    TextureGatherShadow = unchecked((uint)0x82A3),
    ShaderImageLoad = unchecked((uint)0x82A4),
    ShaderImageStore = unchecked((uint)0x82A5),
    ShaderImageAtomic = unchecked((uint)0x82A6),
    ImageTexelSize = unchecked((uint)0x82A7),
    ImageCompatibilityClass = unchecked((uint)0x82A8),
    ImagePixelFormat = unchecked((uint)0x82A9),
    ImagePixelType = unchecked((uint)0x82AA),
    SimultaneousTextureAndDepthTest = unchecked((uint)0x82AC),
    SimultaneousTextureAndStencilTest = unchecked((uint)0x82AD),
    SimultaneousTextureAndDepthWrite = unchecked((uint)0x82AE),
    SimultaneousTextureAndStencilWrite = unchecked((uint)0x82AF),
    TextureCompressedBlockWidth = unchecked((uint)0x82B1),
    TextureCompressedBlockHeight = unchecked((uint)0x82B2),
    TextureCompressedBlockSize = unchecked((uint)0x82B3),
    ClearBuffer = unchecked((uint)0x82B4),
    TextureView = unchecked((uint)0x82B5),
    ViewCompatibilityClass = unchecked((uint)0x82B6),
    ClearTexture = unchecked((uint)0x9365),
    NumSurfaceCompressionFixedRatesEXT = unchecked((uint)0x8F6E),
}
