// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// Ported from the OpenGL headers and corresponding dependencies.
// Original source is Copyright 2013-2020 The Khronos Group Inc. Licensed under the MIT license.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Silk.NET.OpenGL;

[Transformed]
public enum TextureTarget : uint
{
    Texture1D = unchecked((uint)0x0DE0),
    Texture2D = unchecked((uint)0x0DE1),
    ProxyTexture1D = unchecked((uint)0x8063),
    ProxyTexture2D = unchecked((uint)0x8064),
    Texture3D = unchecked((uint)0x806F),
    ProxyTexture3D = unchecked((uint)0x8070),
    TextureCubeMap = unchecked((uint)0x8513),
    TextureCubeMapPositiveX = unchecked((uint)0x8515),
    TextureCubeMapNegativeX = unchecked((uint)0x8516),
    TextureCubeMapPositiveY = unchecked((uint)0x8517),
    TextureCubeMapNegativeY = unchecked((uint)0x8518),
    TextureCubeMapPositiveZ = unchecked((uint)0x8519),
    TextureCubeMapNegativeZ = unchecked((uint)0x851A),
    ProxyTextureCubeMap = unchecked((uint)0x851B),
    Texture1DArray = unchecked((uint)0x8C18),
    ProxyTexture1DArray = unchecked((uint)0x8C19),
    Texture2DArray = unchecked((uint)0x8C1A),
    ProxyTexture2DArray = unchecked((uint)0x8C1B),
    Renderbuffer = unchecked((uint)0x8D41),
    TextureBuffer = unchecked((uint)0x8C2A),
    TextureRectAngle = unchecked((uint)0x84F5),
    ProxyTextureRectAngle = unchecked((uint)0x84F7),
    Texture2DMultisample = unchecked((uint)0x9100),
    ProxyTexture2DMultisample = unchecked((uint)0x9101),
    Texture2DMultisampleArray = unchecked((uint)0x9102),
    ProxyTexture2DMultisampleArray = unchecked((uint)0x9103),
    TextureCubeMapArray = unchecked((uint)0x9009),
    ProxyTextureCubeMapArray = unchecked((uint)0x900B),
    TextureCubeMapARB = unchecked((uint)0x8513),
    TextureCubeMapPositiveXARB = unchecked((uint)0x8515),
    TextureCubeMapNegativeXARB = unchecked((uint)0x8516),
    TextureCubeMapPositiveYARB = unchecked((uint)0x8517),
    TextureCubeMapNegativeYARB = unchecked((uint)0x8518),
    TextureCubeMapPositiveZARB = unchecked((uint)0x8519),
    TextureCubeMapNegativeZARB = unchecked((uint)0x851A),
    ProxyTextureCubeMapARB = unchecked((uint)0x851B),
    TextureCubeMapArrayARB = unchecked((uint)0x9009),
    ProxyTextureCubeMapArrayARB = unchecked((uint)0x900B),
    TextureRectangleARB = unchecked((uint)0x84F5),
    ProxyTextureRectangleARB = unchecked((uint)0x84F7),
    ProxyTexture1DEXT = unchecked((uint)0x8063),
    ProxyTexture2DEXT = unchecked((uint)0x8064),
    Texture3DEXT = unchecked((uint)0x806F),
    ProxyTexture3DEXT = unchecked((uint)0x8070),
    ProxyTexture1DArrayEXT = unchecked((uint)0x8C19),
    ProxyTexture2DArrayEXT = unchecked((uint)0x8C1B),
    TextureCubeMapEXT = unchecked((uint)0x8513),
    TextureCubeMapPositiveXEXT = unchecked((uint)0x8515),
    TextureCubeMapNegativeXEXT = unchecked((uint)0x8516),
    TextureCubeMapPositiveYEXT = unchecked((uint)0x8517),
    TextureCubeMapNegativeYEXT = unchecked((uint)0x8518),
    TextureCubeMapPositiveZEXT = unchecked((uint)0x8519),
    TextureCubeMapNegativeZEXT = unchecked((uint)0x851A),
    ProxyTextureCubeMapEXT = unchecked((uint)0x851B),
    TextureRectangleNV = unchecked((uint)0x84F5),
    ProxyTextureRectangleNV = unchecked((uint)0x84F7),
    DetailTexture2DSGIS = unchecked((uint)0x8095),
    Texture4DSGIS = unchecked((uint)0x8134),
    ProxyTexture4DSGIS = unchecked((uint)0x8135),
    Texture3DOES = unchecked((uint)0x806F),
    TextureCubeMapArrayOES = unchecked((uint)0x9009),
    TextureCubeMapArrayEXT = unchecked((uint)0x9009),
    TextureCubeMapOES = unchecked((uint)0x8513),
    TextureCubeMapPositiveXOES = unchecked((uint)0x8515),
    TextureCubeMapNegativeXOES = unchecked((uint)0x8516),
    TextureCubeMapPositiveYOES = unchecked((uint)0x8517),
    TextureCubeMapNegativeYOES = unchecked((uint)0x8518),
    TextureCubeMapPositiveZOES = unchecked((uint)0x8519),
    TextureCubeMapNegativeZOES = unchecked((uint)0x851A),
}
