// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// Ported from the OpenGL headers and corresponding dependencies.
// Original source is Copyright 2013-2020 The Khronos Group Inc. Licensed under the MIT license.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Silk.NET.OpenGL;

[Transformed]
public enum TextureParameterName : uint
{
    TextureWidth = unchecked((uint)0x1000),
    TextureHeight = unchecked((uint)0x1001),
    TextureBorderColor = unchecked((uint)0x1004),
    TextureMagFilter = unchecked((uint)0x2800),
    TextureMinFilter = unchecked((uint)0x2801),
    TextureWrapS = unchecked((uint)0x2802),
    TextureWrapT = unchecked((uint)0x2803),
    TextureComponents = unchecked((uint)0x1003),
    TextureBorder = unchecked((uint)0x1005),
    TextureInternalFormat = unchecked((uint)0x1003),
    TextureRedSize = unchecked((uint)0x805C),
    TextureGreenSize = unchecked((uint)0x805D),
    TextureBlueSize = unchecked((uint)0x805E),
    TextureAlphaSize = unchecked((uint)0x805F),
    TextureLuminanceSize = unchecked((uint)0x8060),
    TextureIntensitySize = unchecked((uint)0x8061),
    TexturePriority = unchecked((uint)0x8066),
    TextureResident = unchecked((uint)0x8067),
    TextureWrapR = unchecked((uint)0x8072),
    TextureMinLod = unchecked((uint)0x813A),
    TextureMaxLod = unchecked((uint)0x813B),
    TextureBaseLevel = unchecked((uint)0x813C),
    TextureMaxLevel = unchecked((uint)0x813D),
    TextureLodBias = unchecked((uint)0x8501),
    TextureCompareMode = unchecked((uint)0x884C),
    TextureCompareFunc = unchecked((uint)0x884D),
    GenerateMipmap = unchecked((uint)0x8191),
    TextureSwizzleR = unchecked((uint)0x8E42),
    TextureSwizzleG = unchecked((uint)0x8E43),
    TextureSwizzleB = unchecked((uint)0x8E44),
    TextureSwizzleA = unchecked((uint)0x8E45),
    TextureSwizzleRgba = unchecked((uint)0x8E46),
    DepthStencilTextureMode = unchecked((uint)0x90EA),
    TextureMaxAnisotropy = unchecked((uint)0x84FE),
    TextureTilingEXT = unchecked((uint)0x9580),
    TextureDepthEXT = unchecked((uint)0x8071),
    TextureWrapREXT = unchecked((uint)0x8072),
    TexturePriorityEXT = unchecked((uint)0x8066),
    TextureMemoryLayoutIntel = unchecked((uint)0x83FF),
    DetailTextureLevelSGIS = unchecked((uint)0x809A),
    DetailTextureModeSGIS = unchecked((uint)0x809B),
    DetailTextureFuncPointsSGIS = unchecked((uint)0x809C),
    GenerateMipmapSGIS = unchecked((uint)0x8191),
    SharpenTextureFuncPointsSGIS = unchecked((uint)0x80B0),
    Texture4DsizeSGIS = unchecked((uint)0x8136),
    TextureWrapQSGIS = unchecked((uint)0x8137),
    TextureFilter4SizeSGIS = unchecked((uint)0x8147),
    TextureMinLodSGIS = unchecked((uint)0x813A),
    TextureMaxLodSGIS = unchecked((uint)0x813B),
    TextureBaseLevelSGIS = unchecked((uint)0x813C),
    TextureMaxLevelSGIS = unchecked((uint)0x813D),
    DualTextureSelectSGIS = unchecked((uint)0x8124),
    QuadTextureSelectSGIS = unchecked((uint)0x8125),
    TextureClipmapCenterSGIX = unchecked((uint)0x8171),
    TextureClipmapFrameSGIX = unchecked((uint)0x8172),
    TextureClipmapOffsetSGIX = unchecked((uint)0x8173),
    TextureClipmapVirtualDepthSGIX = unchecked((uint)0x8174),
    TextureClipmapLodOffsetSGIX = unchecked((uint)0x8175),
    TextureClipmapDepthSGIX = unchecked((uint)0x8176),
    TextureCompareSGIX = unchecked((uint)0x819A),
    TextureCompareOperatorSGIX = unchecked((uint)0x819B),
    TextureLequalRSGIX = unchecked((uint)0x819C),
    TextureGequalRSGIX = unchecked((uint)0x819D),
    ShadowAmbientSGIX = unchecked((uint)0x80BF),
    TextureMaxClampSSGIX = unchecked((uint)0x8369),
    TextureMaxClampTSGIX = unchecked((uint)0x836A),
    TextureMaxClampRSGIX = unchecked((uint)0x836B),
    TextureLodBiasSSGIX = unchecked((uint)0x818E),
    TextureLodBiasTSGIX = unchecked((uint)0x818F),
    TextureLodBiasRSGIX = unchecked((uint)0x8190),
    PostTextureFilterBiasSGIX = unchecked((uint)0x8179),
    PostTextureFilterScaleSGIX = unchecked((uint)0x817A),
    TextureWrapROES = unchecked((uint)0x8072),
    TextureUnnormalizedCoordinatesARM = unchecked((uint)0x8F6A),
    TextureBorderColorNV = unchecked((uint)0x1004),
    TextureFoveatedCutoffDensityQCOM = unchecked((uint)0x96A0),
}
