// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3dcommon.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

/// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE"]/*'/>
public enum D3D_PRIMITIVE
{
    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_UNDEFINED"]/*'/>

    D3D_PRIMITIVE_UNDEFINED = 0,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_POINT"]/*'/>

    D3D_PRIMITIVE_POINT = 1,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_LINE"]/*'/>

    D3D_PRIMITIVE_LINE = 2,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_TRIANGLE"]/*'/>

    D3D_PRIMITIVE_TRIANGLE = 3,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_LINE_ADJ"]/*'/>

    D3D_PRIMITIVE_LINE_ADJ = 6,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_TRIANGLE_ADJ"]/*'/>

    D3D_PRIMITIVE_TRIANGLE_ADJ = 7,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_1_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_1_CONTROL_POINT_PATCH = 8,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_2_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_2_CONTROL_POINT_PATCH = 9,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_3_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_3_CONTROL_POINT_PATCH = 10,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_4_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_4_CONTROL_POINT_PATCH = 11,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_5_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_5_CONTROL_POINT_PATCH = 12,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_6_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_6_CONTROL_POINT_PATCH = 13,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_7_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_7_CONTROL_POINT_PATCH = 14,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_8_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_8_CONTROL_POINT_PATCH = 15,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_9_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_9_CONTROL_POINT_PATCH = 16,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_10_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_10_CONTROL_POINT_PATCH = 17,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_11_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_11_CONTROL_POINT_PATCH = 18,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_12_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_12_CONTROL_POINT_PATCH = 19,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_13_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_13_CONTROL_POINT_PATCH = 20,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_14_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_14_CONTROL_POINT_PATCH = 21,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_15_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_15_CONTROL_POINT_PATCH = 22,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_16_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_16_CONTROL_POINT_PATCH = 23,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_17_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_17_CONTROL_POINT_PATCH = 24,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_18_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_18_CONTROL_POINT_PATCH = 25,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_19_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_19_CONTROL_POINT_PATCH = 26,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_20_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_20_CONTROL_POINT_PATCH = 27,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_21_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_21_CONTROL_POINT_PATCH = 28,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_22_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_22_CONTROL_POINT_PATCH = 29,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_23_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_23_CONTROL_POINT_PATCH = 30,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_24_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_24_CONTROL_POINT_PATCH = 31,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_25_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_25_CONTROL_POINT_PATCH = 32,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_26_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_26_CONTROL_POINT_PATCH = 33,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_27_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_27_CONTROL_POINT_PATCH = 34,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_28_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_28_CONTROL_POINT_PATCH = 35,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_29_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_29_CONTROL_POINT_PATCH = 36,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_30_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_30_CONTROL_POINT_PATCH = 37,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_31_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_31_CONTROL_POINT_PATCH = 38,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D_PRIMITIVE_32_CONTROL_POINT_PATCH"]/*'/>

    D3D_PRIMITIVE_32_CONTROL_POINT_PATCH = 39,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D10_PRIMITIVE_UNDEFINED"]/*'/>

    D3D10_PRIMITIVE_UNDEFINED = D3D_PRIMITIVE_UNDEFINED,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D10_PRIMITIVE_POINT"]/*'/>

    D3D10_PRIMITIVE_POINT = D3D_PRIMITIVE_POINT,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D10_PRIMITIVE_LINE"]/*'/>

    D3D10_PRIMITIVE_LINE = D3D_PRIMITIVE_LINE,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D10_PRIMITIVE_TRIANGLE"]/*'/>

    D3D10_PRIMITIVE_TRIANGLE = D3D_PRIMITIVE_TRIANGLE,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D10_PRIMITIVE_LINE_ADJ"]/*'/>

    D3D10_PRIMITIVE_LINE_ADJ = D3D_PRIMITIVE_LINE_ADJ,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D10_PRIMITIVE_TRIANGLE_ADJ"]/*'/>

    D3D10_PRIMITIVE_TRIANGLE_ADJ = D3D_PRIMITIVE_TRIANGLE_ADJ,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_UNDEFINED"]/*'/>

    D3D11_PRIMITIVE_UNDEFINED = D3D_PRIMITIVE_UNDEFINED,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_POINT"]/*'/>

    D3D11_PRIMITIVE_POINT = D3D_PRIMITIVE_POINT,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_LINE"]/*'/>

    D3D11_PRIMITIVE_LINE = D3D_PRIMITIVE_LINE,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_TRIANGLE"]/*'/>

    D3D11_PRIMITIVE_TRIANGLE = D3D_PRIMITIVE_TRIANGLE,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_LINE_ADJ"]/*'/>

    D3D11_PRIMITIVE_LINE_ADJ = D3D_PRIMITIVE_LINE_ADJ,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_TRIANGLE_ADJ"]/*'/>

    D3D11_PRIMITIVE_TRIANGLE_ADJ = D3D_PRIMITIVE_TRIANGLE_ADJ,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH = D3D_PRIMITIVE_1_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH = D3D_PRIMITIVE_2_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH = D3D_PRIMITIVE_3_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH = D3D_PRIMITIVE_4_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH = D3D_PRIMITIVE_5_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH = D3D_PRIMITIVE_6_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH = D3D_PRIMITIVE_7_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH = D3D_PRIMITIVE_8_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH = D3D_PRIMITIVE_9_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH = D3D_PRIMITIVE_10_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH = D3D_PRIMITIVE_11_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH = D3D_PRIMITIVE_12_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH = D3D_PRIMITIVE_13_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH = D3D_PRIMITIVE_14_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH = D3D_PRIMITIVE_15_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH = D3D_PRIMITIVE_16_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH = D3D_PRIMITIVE_17_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH = D3D_PRIMITIVE_18_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH = D3D_PRIMITIVE_19_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH = D3D_PRIMITIVE_20_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH = D3D_PRIMITIVE_21_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH = D3D_PRIMITIVE_22_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH = D3D_PRIMITIVE_23_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH = D3D_PRIMITIVE_24_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH = D3D_PRIMITIVE_25_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH = D3D_PRIMITIVE_26_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH = D3D_PRIMITIVE_27_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH = D3D_PRIMITIVE_28_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH = D3D_PRIMITIVE_29_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH = D3D_PRIMITIVE_30_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH = D3D_PRIMITIVE_31_CONTROL_POINT_PATCH,

    /// <include file='D3D_PRIMITIVE.xml' path='doc/member[@name="D3D_PRIMITIVE.D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH"]/*'/>

    D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH = D3D_PRIMITIVE_32_CONTROL_POINT_PATCH,
}
