// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3dcommon.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

/// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING"]/*'/>
public enum D3D_TESSELLATOR_PARTITIONING
{
    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D_TESSELLATOR_PARTITIONING_UNDEFINED"]/*'/>

    D3D_TESSELLATOR_PARTITIONING_UNDEFINED = 0,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D_TESSELLATOR_PARTITIONING_INTEGER"]/*'/>

    D3D_TESSELLATOR_PARTITIONING_INTEGER = 1,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D_TESSELLATOR_PARTITIONING_POW2"]/*'/>

    D3D_TESSELLATOR_PARTITIONING_POW2 = 2,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD"]/*'/>

    D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD = 3,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN"]/*'/>

    D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN = 4,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D11_TESSELLATOR_PARTITIONING_UNDEFINED"]/*'/>

    D3D11_TESSELLATOR_PARTITIONING_UNDEFINED = D3D_TESSELLATOR_PARTITIONING_UNDEFINED,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D11_TESSELLATOR_PARTITIONING_INTEGER"]/*'/>

    D3D11_TESSELLATOR_PARTITIONING_INTEGER = D3D_TESSELLATOR_PARTITIONING_INTEGER,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D11_TESSELLATOR_PARTITIONING_POW2"]/*'/>

    D3D11_TESSELLATOR_PARTITIONING_POW2 = D3D_TESSELLATOR_PARTITIONING_POW2,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD"]/*'/>

    D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD = D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD,

    /// <include file='D3D_TESSELLATOR_PARTITIONING.xml' path='doc/member[@name="D3D_TESSELLATOR_PARTITIONING.D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN"]/*'/>

    D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN = D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN,
}
