// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/directmanipulation.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;
using System.Runtime.Versioning;

namespace Silk.NET.DirectX;
/// <include file='DIRECTMANIPULATION_VERTICALALIGNMENT.xml' path='doc/member[@name="DIRECTMANIPULATION_VERTICALALIGNMENT"]/*'/>
[Flags]
[SupportedOSPlatform("windows6.2")]
public enum DIRECTMANIPULATION_VERTICALALIGNMENT
{
    /// <include file='DIRECTMANIPULATION_VERTICALALIGNMENT.xml' path='doc/member[@name="DIRECTMANIPULATION_VERTICALALIGNMENT.DIRECTMANIPULATION_VERTICALALIGNMENT_NONE"]/*'/>
    DIRECTMANIPULATION_VERTICALALIGNMENT_NONE = 0,
    /// <include file='DIRECTMANIPULATION_VERTICALALIGNMENT.xml' path='doc/member[@name="DIRECTMANIPULATION_VERTICALALIGNMENT.DIRECTMANIPULATION_VERTICALALIGNMENT_TOP"]/*'/>
    DIRECTMANIPULATION_VERTICALALIGNMENT_TOP = 0x1,
    /// <include file='DIRECTMANIPULATION_VERTICALALIGNMENT.xml' path='doc/member[@name="DIRECTMANIPULATION_VERTICALALIGNMENT.DIRECTMANIPULATION_VERTICALALIGNMENT_CENTER"]/*'/>
    DIRECTMANIPULATION_VERTICALALIGNMENT_CENTER = 0x2,
    /// <include file='DIRECTMANIPULATION_VERTICALALIGNMENT.xml' path='doc/member[@name="DIRECTMANIPULATION_VERTICALALIGNMENT.DIRECTMANIPULATION_VERTICALALIGNMENT_BOTTOM"]/*'/>
    DIRECTMANIPULATION_VERTICALALIGNMENT_BOTTOM = 0x4,
    /// <include file='DIRECTMANIPULATION_VERTICALALIGNMENT.xml' path='doc/member[@name="DIRECTMANIPULATION_VERTICALALIGNMENT.DIRECTMANIPULATION_VERTICALALIGNMENT_UNLOCKCENTER"]/*'/>
    DIRECTMANIPULATION_VERTICALALIGNMENT_UNLOCKCENTER = 0x8,
}