// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
namespace Silk.NET.DirectX;
/// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS"]/*'/>
public enum D3D12_BARRIER_ACCESS
{
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_COMMON"]/*'/>
    D3D12_BARRIER_ACCESS_COMMON = 0,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VERTEX_BUFFER"]/*'/>
    D3D12_BARRIER_ACCESS_VERTEX_BUFFER = 0x1,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_CONSTANT_BUFFER"]/*'/>
    D3D12_BARRIER_ACCESS_CONSTANT_BUFFER = 0x2,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_INDEX_BUFFER"]/*'/>
    D3D12_BARRIER_ACCESS_INDEX_BUFFER = 0x4,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_RENDER_TARGET"]/*'/>
    D3D12_BARRIER_ACCESS_RENDER_TARGET = 0x8,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_UNORDERED_ACCESS"]/*'/>
    D3D12_BARRIER_ACCESS_UNORDERED_ACCESS = 0x10,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_DEPTH_STENCIL_WRITE"]/*'/>
    D3D12_BARRIER_ACCESS_DEPTH_STENCIL_WRITE = 0x20,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_DEPTH_STENCIL_READ"]/*'/>
    D3D12_BARRIER_ACCESS_DEPTH_STENCIL_READ = 0x40,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_SHADER_RESOURCE"]/*'/>
    D3D12_BARRIER_ACCESS_SHADER_RESOURCE = 0x80,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_STREAM_OUTPUT"]/*'/>
    D3D12_BARRIER_ACCESS_STREAM_OUTPUT = 0x100,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_INDIRECT_ARGUMENT"]/*'/>
    D3D12_BARRIER_ACCESS_INDIRECT_ARGUMENT = 0x200,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_PREDICATION"]/*'/>
    D3D12_BARRIER_ACCESS_PREDICATION = 0x200,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_COPY_DEST"]/*'/>
    D3D12_BARRIER_ACCESS_COPY_DEST = 0x400,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_COPY_SOURCE"]/*'/>
    D3D12_BARRIER_ACCESS_COPY_SOURCE = 0x800,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_RESOLVE_DEST"]/*'/>
    D3D12_BARRIER_ACCESS_RESOLVE_DEST = 0x1000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_RESOLVE_SOURCE"]/*'/>
    D3D12_BARRIER_ACCESS_RESOLVE_SOURCE = 0x2000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_READ"]/*'/>
    D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_READ = 0x4000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_WRITE"]/*'/>
    D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_WRITE = 0x8000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_SHADING_RATE_SOURCE"]/*'/>
    D3D12_BARRIER_ACCESS_SHADING_RATE_SOURCE = 0x10000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VIDEO_DECODE_READ"]/*'/>
    D3D12_BARRIER_ACCESS_VIDEO_DECODE_READ = 0x20000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VIDEO_DECODE_WRITE"]/*'/>
    D3D12_BARRIER_ACCESS_VIDEO_DECODE_WRITE = 0x40000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VIDEO_PROCESS_READ"]/*'/>
    D3D12_BARRIER_ACCESS_VIDEO_PROCESS_READ = 0x80000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VIDEO_PROCESS_WRITE"]/*'/>
    D3D12_BARRIER_ACCESS_VIDEO_PROCESS_WRITE = 0x100000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VIDEO_ENCODE_READ"]/*'/>
    D3D12_BARRIER_ACCESS_VIDEO_ENCODE_READ = 0x200000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_VIDEO_ENCODE_WRITE"]/*'/>
    D3D12_BARRIER_ACCESS_VIDEO_ENCODE_WRITE = 0x400000,
    /// <include file='D3D12_BARRIER_ACCESS.xml' path='doc/member[@name="D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_NO_ACCESS"]/*'/>
    D3D12_BARRIER_ACCESS_NO_ACCESS = unchecked((int)(0x80000000)),
}