// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
namespace Silk.NET.DirectX;
/// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING"]/*'/>
public enum D3D12_SHADER_COMPONENT_MAPPING
{
    /// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING.D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_0"]/*'/>
    D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_0 = 0,
    /// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING.D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_1"]/*'/>
    D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_1 = 1,
    /// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING.D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_2"]/*'/>
    D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_2 = 2,
    /// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING.D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_3"]/*'/>
    D3D12_SHADER_COMPONENT_MAPPING_FROM_MEMORY_COMPONENT_3 = 3,
    /// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING.D3D12_SHADER_COMPONENT_MAPPING_FORCE_VALUE_0"]/*'/>
    D3D12_SHADER_COMPONENT_MAPPING_FORCE_VALUE_0 = 4,
    /// <include file='D3D12_SHADER_COMPONENT_MAPPING.xml' path='doc/member[@name="D3D12_SHADER_COMPONENT_MAPPING.D3D12_SHADER_COMPONENT_MAPPING_FORCE_VALUE_1"]/*'/>
    D3D12_SHADER_COMPONENT_MAPPING_FORCE_VALUE_1 = 5,
}