// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
using System;
using static Silk.NET.DirectX.D3D12_COMMAND_LIST_TYPE;

namespace Silk.NET.DirectX;
/// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS"]/*'/>
[Flags]
public enum D3D12_COMMAND_LIST_SUPPORT_FLAGS
{
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_NONE"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_NONE = 0,
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_DIRECT"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_DIRECT = (1 << D3D12_COMMAND_LIST_TYPE_DIRECT),
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_BUNDLE"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_BUNDLE = (1 << D3D12_COMMAND_LIST_TYPE_BUNDLE),
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_COMPUTE"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_COMPUTE = (1 << D3D12_COMMAND_LIST_TYPE_COMPUTE),
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_COPY"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_COPY = (1 << D3D12_COMMAND_LIST_TYPE_COPY),
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_DECODE"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_DECODE = (1 << D3D12_COMMAND_LIST_TYPE_VIDEO_DECODE),
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_PROCESS"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_PROCESS = (1 << D3D12_COMMAND_LIST_TYPE_VIDEO_PROCESS),
    /// <include file='D3D12_COMMAND_LIST_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_COMMAND_LIST_SUPPORT_FLAGS.D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_ENCODE"]/*'/>
    D3D12_COMMAND_LIST_SUPPORT_FLAG_VIDEO_ENCODE = (1 << D3D12_COMMAND_LIST_TYPE_VIDEO_ENCODE),
}