// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
namespace TerraFX.Interop.DirectX;
/// <include file='D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.xml' path='doc/member[@name="D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS"]/*'/>
public enum D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS
{
    /// <include file='D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.xml' path='doc/member[@name="D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.D3D12_DRIVER_MATCHING_IDENTIFIER_COMPATIBLE_WITH_DEVICE"]/*'/>
    D3D12_DRIVER_MATCHING_IDENTIFIER_COMPATIBLE_WITH_DEVICE = 0,
    /// <include file='D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.xml' path='doc/member[@name="D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.D3D12_DRIVER_MATCHING_IDENTIFIER_UNSUPPORTED_TYPE"]/*'/>
    D3D12_DRIVER_MATCHING_IDENTIFIER_UNSUPPORTED_TYPE = 0x1,
    /// <include file='D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.xml' path='doc/member[@name="D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.D3D12_DRIVER_MATCHING_IDENTIFIER_UNRECOGNIZED"]/*'/>
    D3D12_DRIVER_MATCHING_IDENTIFIER_UNRECOGNIZED = 0x2,
    /// <include file='D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.xml' path='doc/member[@name="D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_VERSION"]/*'/>
    D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_VERSION = 0x3,
    /// <include file='D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.xml' path='doc/member[@name="D3D12_DRIVER_MATCHING_IDENTIFIER_STATUS.D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_TYPE"]/*'/>
    D3D12_DRIVER_MATCHING_IDENTIFIER_INCOMPATIBLE_TYPE = 0x4,
}