// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace Silk.NET.DirectX;

/// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT"]/*' />
public enum D3D12_BARRIER_LAYOUT
{
    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_UNDEFINED"]/*' />
    D3D12_BARRIER_LAYOUT_UNDEFINED = unchecked((int)(0xffffffff)),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_COMMON = 0,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_PRESENT"]/*' />
    D3D12_BARRIER_LAYOUT_PRESENT = 0,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_GENERIC_READ"]/*' />
    D3D12_BARRIER_LAYOUT_GENERIC_READ = (D3D12_BARRIER_LAYOUT_PRESENT + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_RENDER_TARGET"]/*' />
    D3D12_BARRIER_LAYOUT_RENDER_TARGET = (D3D12_BARRIER_LAYOUT_GENERIC_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_UNORDERED_ACCESS"]/*' />
    D3D12_BARRIER_LAYOUT_UNORDERED_ACCESS = (D3D12_BARRIER_LAYOUT_RENDER_TARGET + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_WRITE = (D3D12_BARRIER_LAYOUT_UNORDERED_ACCESS + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_READ"]/*' />
    D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_READ = (D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_WRITE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_SHADER_RESOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_SHADER_RESOURCE = (D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COPY_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_COPY_SOURCE = (D3D12_BARRIER_LAYOUT_SHADER_RESOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COPY_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_COPY_DEST = (D3D12_BARRIER_LAYOUT_COPY_SOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_RESOLVE_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_RESOLVE_SOURCE = (D3D12_BARRIER_LAYOUT_COPY_DEST + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_RESOLVE_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_RESOLVE_DEST = (D3D12_BARRIER_LAYOUT_RESOLVE_SOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_SHADING_RATE_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_SHADING_RATE_SOURCE = (D3D12_BARRIER_LAYOUT_RESOLVE_DEST + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_DECODE_READ"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_DECODE_READ = (D3D12_BARRIER_LAYOUT_SHADING_RATE_SOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_DECODE_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_DECODE_WRITE = (D3D12_BARRIER_LAYOUT_VIDEO_DECODE_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_READ"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_READ = (D3D12_BARRIER_LAYOUT_VIDEO_DECODE_WRITE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_WRITE = (D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_READ"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_READ = (D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_WRITE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_WRITE = (D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COMMON = (D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_WRITE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ = (D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COMMON + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_UNORDERED_ACCESS"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_UNORDERED_ACCESS = (D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_SHADER_RESOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_SHADER_RESOURCE = (D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_UNORDERED_ACCESS + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_SOURCE = (D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_SHADER_RESOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_DEST = (D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_SOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COMMON = (D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_DEST + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_GENERIC_READ"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_GENERIC_READ = (D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COMMON + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_UNORDERED_ACCESS"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_UNORDERED_ACCESS = (D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_GENERIC_READ + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_SHADER_RESOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_SHADER_RESOURCE = (D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_UNORDERED_ACCESS + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_SOURCE = (D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_SHADER_RESOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_DEST = (D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_SOURCE + 1),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_QUEUE_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_QUEUE_COMMON = (D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_DEST + 1),
}
