// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
using System;

namespace Silk.NET.DirectX;
/// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2"]/*'/>
[Flags]
public enum D3D12_FORMAT_SUPPORT2
{
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_NONE"]/*'/>
    D3D12_FORMAT_SUPPORT2_NONE = 0,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_ADD"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_ADD = 0x1,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_BITWISE_OPS"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_BITWISE_OPS = 0x2,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_COMPARE_STORE_OR_COMPARE_EXCHANGE"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_COMPARE_STORE_OR_COMPARE_EXCHANGE = 0x4,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_EXCHANGE"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_EXCHANGE = 0x8,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_SIGNED_MIN_OR_MAX"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_SIGNED_MIN_OR_MAX = 0x10,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_UNSIGNED_MIN_OR_MAX"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_ATOMIC_UNSIGNED_MIN_OR_MAX = 0x20,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_TYPED_LOAD"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_TYPED_LOAD = 0x40,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_UAV_TYPED_STORE"]/*'/>
    D3D12_FORMAT_SUPPORT2_UAV_TYPED_STORE = 0x80,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_OUTPUT_MERGER_LOGIC_OP"]/*'/>
    D3D12_FORMAT_SUPPORT2_OUTPUT_MERGER_LOGIC_OP = 0x100,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_TILED"]/*'/>
    D3D12_FORMAT_SUPPORT2_TILED = 0x200,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_MULTIPLANE_OVERLAY"]/*'/>
    D3D12_FORMAT_SUPPORT2_MULTIPLANE_OVERLAY = 0x4000,
    /// <include file='D3D12_FORMAT_SUPPORT2.xml' path='doc/member[@name="D3D12_FORMAT_SUPPORT2.D3D12_FORMAT_SUPPORT2_SAMPLER_FEEDBACK"]/*'/>
    D3D12_FORMAT_SUPPORT2_SAMPLER_FEEDBACK = 0x8000,
}