// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/mfcaptureengine.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System.Runtime.Versioning;

namespace Silk.NET.Windows;
/// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY"]/*'/>
[SupportedOSPlatform("windows6.2")]
public enum MF_CAPTURE_ENGINE_STREAM_CATEGORY
{
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_VIDEO_PREVIEW"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_VIDEO_PREVIEW = 0,
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_VIDEO_CAPTURE"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_VIDEO_CAPTURE = 0x1,
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_PHOTO_INDEPENDENT"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_PHOTO_INDEPENDENT = 0x2,
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_PHOTO_DEPENDENT"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_PHOTO_DEPENDENT = 0x3,
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_AUDIO"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_AUDIO = 0x4,
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_UNSUPPORTED"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_UNSUPPORTED = 0x5,
    /// <include file='MF_CAPTURE_ENGINE_STREAM_CATEGORY.xml' path='doc/member[@name="MF_CAPTURE_ENGINE_STREAM_CATEGORY.MF_CAPTURE_ENGINE_STREAM_CATEGORY_METADATA"]/*'/>
    MF_CAPTURE_ENGINE_STREAM_CATEGORY_METADATA = 0x6,
}