// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;

namespace Silk.NET.DirectX;

/// <include file='D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS
{
    /// <include file='D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_NONE"]/*' />
    D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_HEIGHT_ALIGNMENT_MULTIPLE_32_REQUIRED"]/*' />
    D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_HEIGHT_ALIGNMENT_MULTIPLE_32_REQUIRED = 0x1,

    /// <include file='D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_POST_PROCESSING_SUPPORTED"]/*' />
    D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_POST_PROCESSING_SUPPORTED = 0x2,

    /// <include file='D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_REFERENCE_ONLY_ALLOCATIONS_REQUIRED"]/*' />
    D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_REFERENCE_ONLY_ALLOCATIONS_REQUIRED = 0x4,

    /// <include file='D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_DECODE_CONFIGURATION_FLAGS.D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_ALLOW_RESOLUTION_CHANGE_ON_NON_KEY_FRAME"]/*' />
    D3D12_VIDEO_DECODE_CONFIGURATION_FLAG_ALLOW_RESOLUTION_CHANGE_ON_NON_KEY_FRAME = 0x8,
}
