// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
namespace TerraFX.Interop.DirectX;
/// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS"]/*'/>
public enum D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_NONE"]/*'/>
    D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_NONE = 0,
    /// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_RESOLUTION_CHANGE"]/*'/>
    D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_RESOLUTION_CHANGE = 0x1,
    /// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_RATE_CONTROL_CHANGE"]/*'/>
    D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_RATE_CONTROL_CHANGE = 0x2,
    /// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_SUBREGION_LAYOUT_CHANGE"]/*'/>
    D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_SUBREGION_LAYOUT_CHANGE = 0x4,
    /// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_REQUEST_INTRA_REFRESH"]/*'/>
    D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_REQUEST_INTRA_REFRESH = 0x8,
    /// <include file='D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_GOP_SEQUENCE_CHANGE"]/*'/>
    D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAG_GOP_SEQUENCE_CHANGE = 0x10,
}