// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/DocObj.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;

namespace Silk.NET.Windows;
/// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG"]/*'/>
[Flags]
public enum OLECMDID_PAGEACTIONFLAG
{
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_FILEDOWNLOAD"]/*'/>
    OLECMDIDF_PAGEACTION_FILEDOWNLOAD = 0x00000001,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEXINSTALL"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEXINSTALL = 0x00000002,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEXTRUSTFAIL"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEXTRUSTFAIL = 0x00000004,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEXUSERDISABLE"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEXUSERDISABLE = 0x00000008,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEXDISALLOW"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEXDISALLOW = 0x00000010,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEXUNSAFE"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEXUNSAFE = 0x00000020,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_POPUPWINDOW"]/*'/>
    OLECMDIDF_PAGEACTION_POPUPWINDOW = 0x00000040,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_LOCALMACHINE"]/*'/>
    OLECMDIDF_PAGEACTION_LOCALMACHINE = 0x00000080,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_MIMETEXTPLAIN"]/*'/>
    OLECMDIDF_PAGEACTION_MIMETEXTPLAIN = 0x00000100,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE"]/*'/>
    OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE = 0x00000200,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXINSTALL"]/*'/>
    OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXINSTALL = 0x00000200,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_PROTLOCKDOWNLOCALMACHINE"]/*'/>
    OLECMDIDF_PAGEACTION_PROTLOCKDOWNLOCALMACHINE = 0x00000400,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_PROTLOCKDOWNTRUSTED"]/*'/>
    OLECMDIDF_PAGEACTION_PROTLOCKDOWNTRUSTED = 0x00000800,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTRANET"]/*'/>
    OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTRANET = 0x00001000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTERNET"]/*'/>
    OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTERNET = 0x00002000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_PROTLOCKDOWNRESTRICTED"]/*'/>
    OLECMDIDF_PAGEACTION_PROTLOCKDOWNRESTRICTED = 0x00004000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_PROTLOCKDOWNDENY"]/*'/>
    OLECMDIDF_PAGEACTION_PROTLOCKDOWNDENY = 0x00008000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_POPUPALLOWED"]/*'/>
    OLECMDIDF_PAGEACTION_POPUPALLOWED = 0x00010000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_SCRIPTPROMPT"]/*'/>
    OLECMDIDF_PAGEACTION_SCRIPTPROMPT = 0x00020000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEXUSERAPPROVAL"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEXUSERAPPROVAL = 0x00040000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_MIXEDCONTENT"]/*'/>
    OLECMDIDF_PAGEACTION_MIXEDCONTENT = 0x00080000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_INVALID_CERT"]/*'/>
    OLECMDIDF_PAGEACTION_INVALID_CERT = 0x00100000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_INTRANETZONEREQUEST"]/*'/>
    OLECMDIDF_PAGEACTION_INTRANETZONEREQUEST = 0x00200000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_XSSFILTERED"]/*'/>
    OLECMDIDF_PAGEACTION_XSSFILTERED = 0x00400000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_SPOOFABLEIDNHOST"]/*'/>
    OLECMDIDF_PAGEACTION_SPOOFABLEIDNHOST = 0x00800000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_ACTIVEX_EPM_INCOMPATIBLE"]/*'/>
    OLECMDIDF_PAGEACTION_ACTIVEX_EPM_INCOMPATIBLE = 0x01000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXUSERAPPROVAL"]/*'/>
    OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXUSERAPPROVAL = 0x02000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_WPCBLOCKED"]/*'/>
    OLECMDIDF_PAGEACTION_WPCBLOCKED = 0x04000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_WPCBLOCKED_ACTIVEX"]/*'/>
    OLECMDIDF_PAGEACTION_WPCBLOCKED_ACTIVEX = 0x08000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_EXTENSION_COMPAT_BLOCKED"]/*'/>
    OLECMDIDF_PAGEACTION_EXTENSION_COMPAT_BLOCKED = 0x10000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_NORESETACTIVEX"]/*'/>
    OLECMDIDF_PAGEACTION_NORESETACTIVEX = 0x20000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_GENERIC_STATE"]/*'/>
    OLECMDIDF_PAGEACTION_GENERIC_STATE = 0x40000000,
    /// <include file='OLECMDID_PAGEACTIONFLAG.xml' path='doc/member[@name="OLECMDID_PAGEACTIONFLAG.OLECMDIDF_PAGEACTION_RESET"]/*'/>
    OLECMDIDF_PAGEACTION_RESET = unchecked((int)(0x80000000)),
}