// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/DocObj.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;

namespace Silk.NET.Windows;
/// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG"]/*'/>
[Flags]
public enum OLECMDID_REFRESHFLAG
{
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_NORMAL"]/*'/>
    OLECMDIDF_REFRESH_NORMAL = 0,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_IFEXPIRED"]/*'/>
    OLECMDIDF_REFRESH_IFEXPIRED = 1,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_CONTINUE"]/*'/>
    OLECMDIDF_REFRESH_CONTINUE = 2,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_COMPLETELY"]/*'/>
    OLECMDIDF_REFRESH_COMPLETELY = 3,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_NO_CACHE"]/*'/>
    OLECMDIDF_REFRESH_NO_CACHE = 4,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_RELOAD"]/*'/>
    OLECMDIDF_REFRESH_RELOAD = 5,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_LEVELMASK"]/*'/>
    OLECMDIDF_REFRESH_LEVELMASK = 0x00FF,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_CLEARUSERINPUT"]/*'/>
    OLECMDIDF_REFRESH_CLEARUSERINPUT = 0x1000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PROMPTIFOFFLINE"]/*'/>
    OLECMDIDF_REFRESH_PROMPTIFOFFLINE = 0x2000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_THROUGHSCRIPT"]/*'/>
    OLECMDIDF_REFRESH_THROUGHSCRIPT = 0x4000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_SKIPBEFOREUNLOADEVENT"]/*'/>
    OLECMDIDF_REFRESH_SKIPBEFOREUNLOADEVENT = 0x8000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_ACTIVEXINSTALL"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_ACTIVEXINSTALL = 0x00010000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_FILEDOWNLOAD"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_FILEDOWNLOAD = 0x00020000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_LOCALMACHINE"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_LOCALMACHINE = 0x00040000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_POPUPWINDOW"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_POPUPWINDOW = 0x00080000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNLOCALMACHINE"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNLOCALMACHINE = 0x00100000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNTRUSTED"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNTRUSTED = 0x00200000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTRANET"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTRANET = 0x00400000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTERNET"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTERNET = 0x00800000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNRESTRICTED"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNRESTRICTED = 0x01000000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_MIXEDCONTENT"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_MIXEDCONTENT = 0x02000000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_INVALID_CERT"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_INVALID_CERT = 0x04000000,
    /// <include file='OLECMDID_REFRESHFLAG.xml' path='doc/member[@name="OLECMDID_REFRESHFLAG.OLECMDIDF_REFRESH_PAGEACTION_ALLOW_VERSION"]/*'/>
    OLECMDIDF_REFRESH_PAGEACTION_ALLOW_VERSION = 0x08000000,
}