// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/dwrite.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.DirectX;
/// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE"]/*'/>
public enum DWRITE_RENDERING_MODE
{
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_DEFAULT"]/*'/>
    DWRITE_RENDERING_MODE_DEFAULT,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_ALIASED"]/*'/>
    DWRITE_RENDERING_MODE_ALIASED,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_GDI_CLASSIC"]/*'/>
    DWRITE_RENDERING_MODE_GDI_CLASSIC,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_GDI_NATURAL"]/*'/>
    DWRITE_RENDERING_MODE_GDI_NATURAL,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_NATURAL"]/*'/>
    DWRITE_RENDERING_MODE_NATURAL,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_NATURAL_SYMMETRIC"]/*'/>
    DWRITE_RENDERING_MODE_NATURAL_SYMMETRIC,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_OUTLINE"]/*'/>
    DWRITE_RENDERING_MODE_OUTLINE,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_CLEARTYPE_GDI_CLASSIC"]/*'/>
    DWRITE_RENDERING_MODE_CLEARTYPE_GDI_CLASSIC = DWRITE_RENDERING_MODE_GDI_CLASSIC,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_CLEARTYPE_GDI_NATURAL"]/*'/>
    DWRITE_RENDERING_MODE_CLEARTYPE_GDI_NATURAL = DWRITE_RENDERING_MODE_GDI_NATURAL,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_CLEARTYPE_NATURAL"]/*'/>
    DWRITE_RENDERING_MODE_CLEARTYPE_NATURAL = DWRITE_RENDERING_MODE_NATURAL,
    /// <include file='DWRITE_RENDERING_MODE.xml' path='doc/member[@name="DWRITE_RENDERING_MODE.DWRITE_RENDERING_MODE_CLEARTYPE_NATURAL_SYMMETRIC"]/*'/>
    DWRITE_RENDERING_MODE_CLEARTYPE_NATURAL_SYMMETRIC = DWRITE_RENDERING_MODE_NATURAL_SYMMETRIC,
}