// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/winioctl.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace Silk.NET.Windows;

public static partial class QUERY
{
    [NativeTypeName("#define QUERY_DEPENDENT_VOLUME_REQUEST_FLAG_HOST_VOLUMES 0x1")]
    public const int QUERY_DEPENDENT_VOLUME_REQUEST_FLAG_HOST_VOLUMES = 0x1;

    [NativeTypeName("#define QUERY_DEPENDENT_VOLUME_REQUEST_FLAG_GUEST_VOLUMES 0x2")]
    public const int QUERY_DEPENDENT_VOLUME_REQUEST_FLAG_GUEST_VOLUMES = 0x2;

    [NativeTypeName("#define QUERY_FILE_LAYOUT_RESTART (0x00000001)")]
    public const int QUERY_FILE_LAYOUT_RESTART = (0x00000001);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_NAMES (0x00000002)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_NAMES = (0x00000002);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAMS (0x00000004)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAMS = (0x00000004);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_EXTENTS (0x00000008)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_EXTENTS = (0x00000008);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_EXTRA_INFO (0x00000010)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_EXTRA_INFO = (0x00000010);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAMS_WITH_NO_CLUSTERS_ALLOCATED (0x00000020)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAMS_WITH_NO_CLUSTERS_ALLOCATED = (0x00000020);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_FULL_PATH_IN_NAMES (0x00000040)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_FULL_PATH_IN_NAMES = (0x00000040);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION (0x00000080)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION = (0x00000080);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_DSC_ATTRIBUTE (0x00000100)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_DSC_ATTRIBUTE = (0x00000100);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_TXF_ATTRIBUTE (0x00000200)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_TXF_ATTRIBUTE = (0x00000200);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_EFS_ATTRIBUTE (0x00000400)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_EFS_ATTRIBUTE = (0x00000400);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_ONLY_FILES_WITH_SPECIFIC_ATTRIBUTES (0x00000800)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_ONLY_FILES_WITH_SPECIFIC_ATTRIBUTES = (0x00000800);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_FILES_WITH_DSC_ATTRIBUTE (0x00001000)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_FILES_WITH_DSC_ATTRIBUTE = (0x00001000);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_DATA_ATTRIBUTE (0x00002000)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_DATA_ATTRIBUTE = (0x00002000);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_REPARSE_ATTRIBUTE (0x00004000)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_REPARSE_ATTRIBUTE = (0x00004000);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_EA_ATTRIBUTE (0x00008000)")]
    public const int QUERY_FILE_LAYOUT_INCLUDE_STREAM_INFORMATION_FOR_EA_ATTRIBUTE = (0x00008000);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_SINGLE_INSTANCED (0x00000001)")]
    public const int QUERY_FILE_LAYOUT_SINGLE_INSTANCED = (0x00000001);

    [NativeTypeName("#define QUERY_STORAGE_CLASSES_FLAGS_MEASURE_WRITE 0x80000000")]
    public const uint QUERY_STORAGE_CLASSES_FLAGS_MEASURE_WRITE = 0x80000000;

    [NativeTypeName("#define QUERY_STORAGE_CLASSES_FLAGS_MEASURE_READ 0x40000000")]
    public const int QUERY_STORAGE_CLASSES_FLAGS_MEASURE_READ = 0x40000000;

    [NativeTypeName("#define QUERY_STORAGE_CLASSES_FLAGS_NO_DEFRAG_VOLUME 0x20000000")]
    public const int QUERY_STORAGE_CLASSES_FLAGS_NO_DEFRAG_VOLUME = 0x20000000;

    [NativeTypeName("#define QUERY_FILE_LAYOUT_REPARSE_DATA_INVALID (0x0001)")]
    public const int QUERY_FILE_LAYOUT_REPARSE_DATA_INVALID = (0x0001);

    [NativeTypeName("#define QUERY_FILE_LAYOUT_REPARSE_TAG_INVALID (0x0002)")]
    public const int QUERY_FILE_LAYOUT_REPARSE_TAG_INVALID = (0x0002);
}
