// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/mmeapi.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.Windows;
public static partial class MIXERLINE
{
    [NativeTypeName("#define MIXERLINE_LINEF_ACTIVE 0x00000001L")]
    public const int MIXERLINE_LINEF_ACTIVE = 0x00000001;
    [NativeTypeName("#define MIXERLINE_LINEF_DISCONNECTED 0x00008000L")]
    public const int MIXERLINE_LINEF_DISCONNECTED = 0x00008000;
    [NativeTypeName("#define MIXERLINE_LINEF_SOURCE 0x80000000L")]
    public const uint MIXERLINE_LINEF_SOURCE = 0x80000000;
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_FIRST 0x00000000L")]
    public const int MIXERLINE_COMPONENTTYPE_DST_FIRST = 0x00000000;
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_UNDEFINED (MIXERLINE_COMPONENTTYPE_DST_FIRST + 0)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_UNDEFINED = (0x00000000 + 0);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_DIGITAL (MIXERLINE_COMPONENTTYPE_DST_FIRST + 1)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_DIGITAL = (0x00000000 + 1);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_LINE (MIXERLINE_COMPONENTTYPE_DST_FIRST + 2)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_LINE = (0x00000000 + 2);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_MONITOR (MIXERLINE_COMPONENTTYPE_DST_FIRST + 3)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_MONITOR = (0x00000000 + 3);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_SPEAKERS (MIXERLINE_COMPONENTTYPE_DST_FIRST + 4)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_SPEAKERS = (0x00000000 + 4);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_HEADPHONES (MIXERLINE_COMPONENTTYPE_DST_FIRST + 5)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_HEADPHONES = (0x00000000 + 5);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_TELEPHONE (MIXERLINE_COMPONENTTYPE_DST_FIRST + 6)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_TELEPHONE = (0x00000000 + 6);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_WAVEIN (MIXERLINE_COMPONENTTYPE_DST_FIRST + 7)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_WAVEIN = (0x00000000 + 7);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_VOICEIN (MIXERLINE_COMPONENTTYPE_DST_FIRST + 8)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_VOICEIN = (0x00000000 + 8);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_DST_LAST (MIXERLINE_COMPONENTTYPE_DST_FIRST + 8)")]
    public const int MIXERLINE_COMPONENTTYPE_DST_LAST = (0x00000000 + 8);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_FIRST 0x00001000L")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_FIRST = 0x00001000;
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_UNDEFINED (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 0)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_UNDEFINED = (0x00001000 + 0);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_DIGITAL (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 1)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_DIGITAL = (0x00001000 + 1);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_LINE (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 2)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_LINE = (0x00001000 + 2);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_MICROPHONE (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 3)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_MICROPHONE = (0x00001000 + 3);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_SYNTHESIZER (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 4)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_SYNTHESIZER = (0x00001000 + 4);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_COMPACTDISC (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 5)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_COMPACTDISC = (0x00001000 + 5);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_TELEPHONE (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 6)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_TELEPHONE = (0x00001000 + 6);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_PCSPEAKER (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 7)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_PCSPEAKER = (0x00001000 + 7);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_WAVEOUT (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 8)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_WAVEOUT = (0x00001000 + 8);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_AUXILIARY (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 9)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_AUXILIARY = (0x00001000 + 9);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_ANALOG (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 10)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_ANALOG = (0x00001000 + 10);
    [NativeTypeName("#define MIXERLINE_COMPONENTTYPE_SRC_LAST (MIXERLINE_COMPONENTTYPE_SRC_FIRST + 10)")]
    public const int MIXERLINE_COMPONENTTYPE_SRC_LAST = (0x00001000 + 10);
    [NativeTypeName("#define MIXERLINE_TARGETTYPE_UNDEFINED 0")]
    public const int MIXERLINE_TARGETTYPE_UNDEFINED = 0;
    [NativeTypeName("#define MIXERLINE_TARGETTYPE_WAVEOUT 1")]
    public const int MIXERLINE_TARGETTYPE_WAVEOUT = 1;
    [NativeTypeName("#define MIXERLINE_TARGETTYPE_WAVEIN 2")]
    public const int MIXERLINE_TARGETTYPE_WAVEIN = 2;
    [NativeTypeName("#define MIXERLINE_TARGETTYPE_MIDIOUT 3")]
    public const int MIXERLINE_TARGETTYPE_MIDIOUT = 3;
    [NativeTypeName("#define MIXERLINE_TARGETTYPE_MIDIIN 4")]
    public const int MIXERLINE_TARGETTYPE_MIDIIN = 4;
    [NativeTypeName("#define MIXERLINE_TARGETTYPE_AUX 5")]
    public const int MIXERLINE_TARGETTYPE_AUX = 5;
}