// This file is part of Silk.NET.
// 
// You may modify and distribute Silk.NET under the terms
// of the MIT license. See the LICENSE file for details.


using System;

#pragma warning disable 1591

namespace Silk.NET.EGL.Extensions.KHR
{
    public enum KHR
    {
        CLEventHandleKhr = 0x309C,
        SyncCLEventKhr = 0x30FE,
        SyncCLEventCompleteKhr = 0x30FF,
        ConformantKhr = 0x3042,
        VGColorspaceLinearBitKhr = 0x20,
        VGAlphaFormatPreBitKhr = 0x40,
        ContextReleaseBehaviorNoneKhr = 0x0,
        ContextReleaseBehaviorKhr = 0x2097,
        ContextReleaseBehaviorFlushKhr = 0x2098,
        ContextMajorVersionKhr = 0x3098,
        ContextMinorVersionKhr = 0x30FB,
        ContextFlagsKhr = 0x30FC,
        ContextOpenglProfileMaskKhr = 0x30FD,
        ContextOpenglResetNotificationStrategyKhr = 0x31BD,
        NoResetNotificationKhr = 0x31BE,
        LoseContextOnResetKhr = 0x31BF,
        ContextOpenglDebugBitKhr = 0x1,
        ContextOpenglForwardCompatibleBitKhr = 0x2,
        ContextOpenglRobustAccessBitKhr = 0x4,
        ContextOpenglCoreProfileBitKhr = 0x1,
        ContextOpenglCompatibilityProfileBitKhr = 0x2,
        OpenglES3Bit = 0x40,
        OpenglES3BitKhr = 0x40,
        ContextOpenglNoErrorKhr = 0x31B3,
        ObjectThreadKhr = 0x33B0,
        ObjectDisplayKhr = 0x33B1,
        ObjectContextKhr = 0x33B2,
        ObjectSurfaceKhr = 0x33B3,
        ObjectImageKhr = 0x33B4,
        ObjectSyncKhr = 0x33B5,
        ObjectStreamKhr = 0x33B6,
        DebugMsgCriticalKhr = 0x33B9,
        DebugMsgErrorKhr = 0x33BA,
        DebugMsgWarnKhr = 0x33BB,
        DebugMsgInfoKhr = 0x33BC,
        DebugCallbackKhr = 0x33B8,
        TrackReferencesKhr = 0x3352,
        SyncPriorCommandsCompleteKhr = 0x30F0,
        SyncConditionKhr = 0x30F8,
        SyncFenceKhr = 0x30F9,
        GLColorspaceKhr = 0x309D,
        GLColorspaceSrgbKhr = 0x3089,
        GLColorspaceLinearKhr = 0x308A,
        GLRenderbufferKhr = 0x30B9,
        GLTexture2DKhr = 0x30B1,
        GLTextureLevelKhr = 0x30BC,
        GLTexture3DKhr = 0x30B2,
        GLTextureZoffsetKhr = 0x30BD,
        GLTextureCubeMapPositiveXKhr = 0x30B3,
        GLTextureCubeMapNegativeXKhr = 0x30B4,
        GLTextureCubeMapPositiveYKhr = 0x30B5,
        GLTextureCubeMapNegativeYKhr = 0x30B6,
        GLTextureCubeMapPositiveZKhr = 0x30B7,
        GLTextureCubeMapNegativeZKhr = 0x30B8,
        NativePixmapKhr = 0x30B0,
        NoImageKhr = 0x0,
        ImagePreservedKhr = 0x30D2,
        ReadSurfaceBitKhr = 0x1,
        WriteSurfaceBitKhr = 0x2,
        LockSurfaceBitKhr = 0x80,
        OptimalFormatBitKhr = 0x100,
        MatchFormatKhr = 0x3043,
        FormatRgb565ExactKhr = 0x30C0,
        FormatRgb565Khr = 0x30C1,
        FormatRgba8888ExactKhr = 0x30C2,
        FormatRgba8888Khr = 0x30C3,
        MapPreservePixelsKhr = 0x30C4,
        LockUsageHintKhr = 0x30C5,
        BitmapPointerKhr = 0x30C6,
        BitmapPitchKhr = 0x30C7,
        BitmapOriginKhr = 0x30C8,
        BitmapPixelRedOffsetKhr = 0x30C9,
        BitmapPixelGreenOffsetKhr = 0x30CA,
        BitmapPixelBlueOffsetKhr = 0x30CB,
        BitmapPixelAlphaOffsetKhr = 0x30CC,
        BitmapPixelLuminanceOffsetKhr = 0x30CD,
        LowerLeftKhr = 0x30CE,
        UpperLeftKhr = 0x30CF,
        BitmapPixelSizeKhr = 0x3110,
        MutableRenderBufferBitKhr = 0x1000,
        NoConfigKhr = 0x0,
        BufferAgeKhr = 0x313D,
        PlatformAndroidKhr = 0x3141,
        PlatformGbmKhr = 0x31D7,
        PlatformWaylandKhr = 0x31D8,
        PlatformX11Khr = 0x31D5,
        PlatformX11ScreenKhr = 0x31D6,
        SyncStatusKhr = 0x30F1,
        SignaledKhr = 0x30F2,
        UnsignaledKhr = 0x30F3,
        TimeoutExpiredKhr = 0x30F5,
        ConditionSatisfiedKhr = 0x30F6,
        SyncTypeKhr = 0x30F7,
        SyncReusableKhr = 0x30FA,
        SyncFlushCommandsBitKhr = 0x1,
        ForeverKhr = unchecked((int)0xFFFFFFFFFFFFFFFF),
        NoSyncKhr = 0x0,
        NoStreamKhr = 0x0,
        ConsumerLatencyUsecKhr = 0x3210,
        ProducerFrameKhr = 0x3212,
        ConsumerFrameKhr = 0x3213,
        StreamStateKhr = 0x3214,
        StreamStateCreatedKhr = 0x3215,
        StreamStateConnectingKhr = 0x3216,
        StreamStateEmptyKhr = 0x3217,
        StreamStateNewFrameAvailableKhr = 0x3218,
        StreamStateOldFrameAvailableKhr = 0x3219,
        StreamStateDisconnectedKhr = 0x321A,
        BadStreamKhr = 0x321B,
        BadStateKhr = 0x321C,
        ConsumerAcquireTimeoutUsecKhr = 0x321E,
        NoFileDescriptorKhr = unchecked((int)0xFFFFFFFFFFFFFFFF),
        StreamFifoLengthKhr = 0x31FC,
        StreamTimeNowKhr = 0x31FD,
        StreamTimeConsumerKhr = 0x31FE,
        StreamTimeProducerKhr = 0x31FF,
        StreamBitKhr = 0x800,
        VGParentImageKhr = 0x30BA,
    }
}
