#!/usr/bin/env -S bash -eu
IFS=' ' read -a NATIVE_LIBRARY_PATHS_ARRAY <<< "$NATIVE_LIBRARY_PATHS"
IFS=' ' read -a NATIVE_LIBRARY_SUBMODULE_PATHS_ARRAY <<< "$NATIVE_LIBRARY_SUBMODULE_PATHS"
IFS=' ' read -a NATIVE_LIBRARY_SHORTHANDS_ARRAY <<< "$NATIVE_LIBRARY_SHORTHANDS"
NATIVE_LIBRARY_UNIQUE_SHORTHANDS=$(printf "%s\n" "${NATIVE_LIBRARY_SHORTHANDS_ARRAY[@]}" | sort -u)
