// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/AppxPackaging.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;
using System.Runtime.Versioning;

namespace TerraFX.Interop.Windows;
/// <include file='APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.xml' path='doc/member[@name="APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS"]/*'/>
[Flags]
[SupportedOSPlatform("windows10.0")]
public enum APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS
{
    /// <include file='APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.xml' path='doc/member[@name="APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTION_NONE"]/*'/>
    APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTION_NONE = 0,
    /// <include file='APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.xml' path='doc/member[@name="APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTION_SKIP_VALIDATION"]/*'/>
    APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTION_SKIP_VALIDATION = 0x1,
    /// <include file='APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.xml' path='doc/member[@name="APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTION_LOCALIZED"]/*'/>
    APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTION_LOCALIZED = 0x2,
}