// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/imapi2.h in the Windows SDK for Windows 10.0.26100.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.Windows;

[Flags]
public enum IMAPI_FORMAT2_DATA_MEDIA_STATE
{
    IMAPI_FORMAT2_DATA_MEDIA_STATE_UNKNOWN = 0,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_INFORMATIONAL_MASK = 0xf,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_UNSUPPORTED_MASK = 0xfc00,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_OVERWRITE_ONLY = 0x1,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_RANDOMLY_WRITABLE = 0x1,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_BLANK = 0x2,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_APPENDABLE = 0x4,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_FINAL_SESSION = 0x8,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_DAMAGED = 0x400,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_ERASE_REQUIRED = 0x800,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_NON_EMPTY_SESSION = 0x1000,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_WRITE_PROTECTED = 0x2000,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_FINALIZED = 0x4000,
    IMAPI_FORMAT2_DATA_MEDIA_STATE_UNSUPPORTED_MEDIA = 0x8000,
}
