// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/d2d1effects_2.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
namespace TerraFX.Interop.DirectX;
/// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP"]/*'/>
public enum D2D1_HIGHLIGHTSANDSHADOWS_PROP
{
    /// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP.D2D1_HIGHLIGHTSANDSHADOWS_PROP_HIGHLIGHTS"]/*'/>
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_HIGHLIGHTS = 0,
    /// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP.D2D1_HIGHLIGHTSANDSHADOWS_PROP_SHADOWS"]/*'/>
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_SHADOWS = 1,
    /// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP.D2D1_HIGHLIGHTSANDSHADOWS_PROP_CLARITY"]/*'/>
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_CLARITY = 2,
    /// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP.D2D1_HIGHLIGHTSANDSHADOWS_PROP_INPUT_GAMMA"]/*'/>
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_INPUT_GAMMA = 3,
    /// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP.D2D1_HIGHLIGHTSANDSHADOWS_PROP_MASK_BLUR_RADIUS"]/*'/>
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_MASK_BLUR_RADIUS = 4,
    /// <include file='D2D1_HIGHLIGHTSANDSHADOWS_PROP.xml' path='doc/member[@name="D2D1_HIGHLIGHTSANDSHADOWS_PROP.D2D1_HIGHLIGHTSANDSHADOWS_PROP_FORCE_DWORD"]/*'/>
    D2D1_HIGHLIGHTSANDSHADOWS_PROP_FORCE_DWORD = unchecked((int)(0xffffffff)),
}