// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// Generated using the OpenAL Soft headers and corresponding dependencies.
// Original source is licensed under the LGPL 2.0 license. Please note that while bindings are able to be MIT due to
// being header-derived only, implementations of the headers may have a less permissive license.
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Silk.NET.OpenAL;

[Transformed]
public enum EffectPName : uint
{
    ReverbDensity = unchecked((uint)0x0001),
    ReverbDiffusion = unchecked((uint)0x0002),
    ReverbGain = unchecked((uint)0x0003),
    ReverbGainhf = unchecked((uint)0x0004),
    ReverbDecayTime = unchecked((uint)0x0005),
    ReverbDecayHfratio = unchecked((uint)0x0006),
    ReverbReflectionsGain = unchecked((uint)0x0007),
    ReverbReflectionsDelay = unchecked((uint)0x0008),
    ReverbLateReverbGain = unchecked((uint)0x0009),
    ReverbLateReverbDelay = unchecked((uint)0x000A),
    ReverbAirAbsorptionGainhf = unchecked((uint)0x000B),
    ReverbRoomRolloffFactor = unchecked((uint)0x000C),
    ReverbDecayHflimit = unchecked((uint)0x000D),
    EaxreverbDensity = unchecked((uint)0x0001),
    EaxreverbDiffusion = unchecked((uint)0x0002),
    EaxreverbGain = unchecked((uint)0x0003),
    EaxreverbGainhf = unchecked((uint)0x0004),
    EaxreverbGainlf = unchecked((uint)0x0005),
    EaxreverbDecayTime = unchecked((uint)0x0006),
    EaxreverbDecayHfratio = unchecked((uint)0x0007),
    EaxreverbDecayLfratio = unchecked((uint)0x0008),
    EaxreverbReflectionsGain = unchecked((uint)0x0009),
    EaxreverbReflectionsDelay = unchecked((uint)0x000A),
    EaxreverbReflectionsPan = unchecked((uint)0x000B),
    EaxreverbLateReverbGain = unchecked((uint)0x000C),
    EaxreverbLateReverbDelay = unchecked((uint)0x000D),
    EaxreverbLateReverbPan = unchecked((uint)0x000E),
    EaxreverbEchoTime = unchecked((uint)0x000F),
    EaxreverbEchoDepth = unchecked((uint)0x0010),
    EaxreverbModulationTime = unchecked((uint)0x0011),
    EaxreverbModulationDepth = unchecked((uint)0x0012),
    EaxreverbAirAbsorptionGainhf = unchecked((uint)0x0013),
    EaxreverbHfreference = unchecked((uint)0x0014),
    EaxreverbLfreference = unchecked((uint)0x0015),
    EaxreverbRoomRolloffFactor = unchecked((uint)0x0016),
    EaxreverbDecayHflimit = unchecked((uint)0x0017),
    ChorusWaveform = unchecked((uint)0x0001),
    ChorusPhase = unchecked((uint)0x0002),
    ChorusRate = unchecked((uint)0x0003),
    ChorusDepth = unchecked((uint)0x0004),
    ChorusFeedback = unchecked((uint)0x0005),
    ChorusDelay = unchecked((uint)0x0006),
    DistortionEdge = unchecked((uint)0x0001),
    DistortionGain = unchecked((uint)0x0002),
    DistortionLowpassCutoff = unchecked((uint)0x0003),
    DistortionEqcenter = unchecked((uint)0x0004),
    DistortionEqbandwidth = unchecked((uint)0x0005),
    EchoDelay = unchecked((uint)0x0001),
    EchoLrdelay = unchecked((uint)0x0002),
    EchoDamping = unchecked((uint)0x0003),
    EchoFeedback = unchecked((uint)0x0004),
    EchoSpread = unchecked((uint)0x0005),
    FlangerWaveform = unchecked((uint)0x0001),
    FlangerPhase = unchecked((uint)0x0002),
    FlangerRate = unchecked((uint)0x0003),
    FlangerDepth = unchecked((uint)0x0004),
    FlangerFeedback = unchecked((uint)0x0005),
    FlangerDelay = unchecked((uint)0x0006),
    FrequencyShifterFrequency = unchecked((uint)0x0001),
    FrequencyShifterLeftDirection = unchecked((uint)0x0002),
    FrequencyShifterRightDirection = unchecked((uint)0x0003),
    VocalMorpherPhonemea = unchecked((uint)0x0001),
    VocalMorpherPhonemeaCoarseTuning = unchecked((uint)0x0002),
    VocalMorpherPhonemeb = unchecked((uint)0x0003),
    VocalMorpherPhonemebCoarseTuning = unchecked((uint)0x0004),
    VocalMorpherWaveform = unchecked((uint)0x0005),
    VocalMorpherRate = unchecked((uint)0x0006),
    PitchShifterCoarseTune = unchecked((uint)0x0001),
    PitchShifterFineTune = unchecked((uint)0x0002),
    RingModulatorFrequency = unchecked((uint)0x0001),
    RingModulatorHighpassCutoff = unchecked((uint)0x0002),
    RingModulatorWaveform = unchecked((uint)0x0003),
    AutowahAttackTime = unchecked((uint)0x0001),
    AutowahReleaseTime = unchecked((uint)0x0002),
    AutowahResonance = unchecked((uint)0x0003),
    AutowahPeakGain = unchecked((uint)0x0004),
    CompressorOnoff = unchecked((uint)0x0001),
    EqualizerLowGain = unchecked((uint)0x0001),
    EqualizerLowCutoff = unchecked((uint)0x0002),
    EqualizerMid1Gain = unchecked((uint)0x0003),
    EqualizerMid1Center = unchecked((uint)0x0004),
    EqualizerMid1Width = unchecked((uint)0x0005),
    EqualizerMid2Gain = unchecked((uint)0x0006),
    EqualizerMid2Center = unchecked((uint)0x0007),
    EqualizerMid2Width = unchecked((uint)0x0008),
    EqualizerHighGain = unchecked((uint)0x0009),
    EqualizerHighCutoff = unchecked((uint)0x000A),
    EffectType = unchecked((uint)0x8001),
    DedicatedGain = unchecked((uint)0x0001),
}
