// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from um/InteractionContext.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.
using System;
using System.Runtime.Versioning;

namespace TerraFX.Interop.Windows;
/// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS"]/*'/>
[Flags]
[SupportedOSPlatform("windows6.2")]
public enum INTERACTION_CONFIGURATION_FLAGS
{
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_NONE"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_NONE = 0x00000000,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION = 0x00000001,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_X"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_X = 0x00000002,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_Y"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_Y = 0x00000004,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_ROTATION"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_ROTATION = 0x00000008,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_SCALING"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_SCALING = 0x00000010,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_INERTIA"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_TRANSLATION_INERTIA = 0x00000020,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_ROTATION_INERTIA"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_ROTATION_INERTIA = 0x00000040,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_SCALING_INERTIA"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_SCALING_INERTIA = 0x00000080,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_RAILS_X"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_RAILS_X = 0x00000100,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_RAILS_Y"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_RAILS_Y = 0x00000200,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_EXACT"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_EXACT = 0x00000400,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MANIPULATION_MULTIPLE_FINGER_PANNING"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MANIPULATION_MULTIPLE_FINGER_PANNING = 0x00000800,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE = 0x00000001,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_HORIZONTAL"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_HORIZONTAL = 0x00000002,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_SELECT"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_SELECT = 0x00000004,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_SPEED_BUMP"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_SPEED_BUMP = 0x00000008,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_REARRANGE"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_REARRANGE = 0x00000010,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_EXACT"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_CROSS_SLIDE_EXACT = 0x00000020,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_TAP"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_TAP = 0x00000001,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_TAP_DOUBLE"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_TAP_DOUBLE = 0x00000002,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_TAP_MULTIPLE_FINGER"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_TAP_MULTIPLE_FINGER = 0x00000004,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_SECONDARY_TAP"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_SECONDARY_TAP = 0x00000001,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_HOLD"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_HOLD = 0x00000001,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_HOLD_MOUSE"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_HOLD_MOUSE = 0x00000002,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_HOLD_MULTIPLE_FINGER"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_HOLD_MULTIPLE_FINGER = 0x00000004,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_DRAG"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_DRAG = 0x00000001,
    /// <include file='INTERACTION_CONFIGURATION_FLAGS.xml' path='doc/member[@name="INTERACTION_CONFIGURATION_FLAGS.INTERACTION_CONFIGURATION_FLAG_MAX"]/*'/>
    INTERACTION_CONFIGURATION_FLAG_MAX = unchecked((int)(0xffffffff)),
}