// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/d2d1.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace Silk.NET.DirectX;

/// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION"]/*' />
public enum D2D1_INTERPOLATION_MODE_DEFINITION
{
    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_NEAREST_NEIGHBOR"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_NEAREST_NEIGHBOR = 0,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_LINEAR"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_LINEAR = 1,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_CUBIC"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_CUBIC = 2,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_MULTI_SAMPLE_LINEAR"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_MULTI_SAMPLE_LINEAR = 3,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_ANISOTROPIC"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_ANISOTROPIC = 4,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_HIGH_QUALITY_CUBIC"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_HIGH_QUALITY_CUBIC = 5,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_FANT"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_FANT = 6,

    /// <include file='D2D1_INTERPOLATION_MODE_DEFINITION.xml' path='doc/member[@name="D2D1_INTERPOLATION_MODE_DEFINITION.D2D1_INTERPOLATION_MODE_DEFINITION_MIPMAP_LINEAR"]/*' />
    D2D1_INTERPOLATION_MODE_DEFINITION_MIPMAP_LINEAR = 7,
}
