// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.606.4
// Original source is Copyright © Microsoft. Licensed under the MIT license
namespace Silk.NET.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS"]/*'/>
public enum D3D12_VIDEO_ENCODER_SUPPORT_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_NONE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_GENERAL_SUPPORT_OK"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_GENERAL_SUPPORT_OK = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_RECONFIGURATION_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_RECONFIGURATION_AVAILABLE = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RESOLUTION_RECONFIGURATION_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RESOLUTION_RECONFIGURATION_AVAILABLE = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_VBV_SIZE_CONFIG_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_VBV_SIZE_CONFIG_AVAILABLE = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_FRAME_ANALYSIS_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_FRAME_ANALYSIS_AVAILABLE = 0x10,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RECONSTRUCTED_FRAMES_REQUIRE_TEXTURE_ARRAYS"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RECONSTRUCTED_FRAMES_REQUIRE_TEXTURE_ARRAYS = 0x20,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_DELTA_QP_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_DELTA_QP_AVAILABLE = 0x40,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_SUBREGION_LAYOUT_RECONFIGURATION_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_SUBREGION_LAYOUT_RECONFIGURATION_AVAILABLE = 0x80,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_ADJUSTABLE_QP_RANGE_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_ADJUSTABLE_QP_RANGE_AVAILABLE = 0x100,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_INITIAL_QP_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_INITIAL_QP_AVAILABLE = 0x200,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_MAX_FRAME_SIZE_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_RATE_CONTROL_MAX_FRAME_SIZE_AVAILABLE = 0x400,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_SEQUENCE_GOP_RECONFIGURATION_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_SEQUENCE_GOP_RECONFIGURATION_AVAILABLE = 0x800,

    /// <include file='D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.D3D12_VIDEO_ENCODER_SUPPORT_FLAG_MOTION_ESTIMATION_PRECISION_MODE_LIMIT_AVAILABLE"]/*'/>

    D3D12_VIDEO_ENCODER_SUPPORT_FLAG_MOTION_ESTIMATION_PRECISION_MODE_LIMIT_AVAILABLE = 0x1000,
}
