// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

public enum D3D12_RENDER_PASS_ENDING_ACCESS_TYPE
{
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_DISCARD = 0,
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE =
        (D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_DISCARD + 1),
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_RESOLVE =
        (D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE + 1),
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_NO_ACCESS =
        (D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_RESOLVE + 1),
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE_LOCAL_RENDER =
        (D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_NO_ACCESS + 1),
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE_LOCAL_SRV =
        (D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE_LOCAL_RENDER + 1),
    D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE_LOCAL_UAV =
        (D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE_LOCAL_SRV + 1),
}
