// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

public enum D3D12_STATE_SUBOBJECT_TYPE
{
    D3D12_STATE_SUBOBJECT_TYPE_STATE_OBJECT_CONFIG = 0,
    D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE = 1,
    D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE = 2,
    D3D12_STATE_SUBOBJECT_TYPE_NODE_MASK = 3,
    D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY = 5,
    D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION = 6,
    D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_EXPORTS_ASSOCIATION = 7,
    D3D12_STATE_SUBOBJECT_TYPE_DXIL_SUBOBJECT_TO_EXPORTS_ASSOCIATION = 8,
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG = 9,
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG = 10,
    D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP = 11,
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG1 = 12,
    D3D12_STATE_SUBOBJECT_TYPE_WORK_GRAPH = 13,
    D3D12_STATE_SUBOBJECT_TYPE_STREAM_OUTPUT = 14,
    D3D12_STATE_SUBOBJECT_TYPE_BLEND = 15,
    D3D12_STATE_SUBOBJECT_TYPE_SAMPLE_MASK = 16,
    D3D12_STATE_SUBOBJECT_TYPE_RASTERIZER = 17,
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL = 18,
    D3D12_STATE_SUBOBJECT_TYPE_INPUT_LAYOUT = 19,
    D3D12_STATE_SUBOBJECT_TYPE_IB_STRIP_CUT_VALUE = 20,
    D3D12_STATE_SUBOBJECT_TYPE_PRIMITIVE_TOPOLOGY = 21,
    D3D12_STATE_SUBOBJECT_TYPE_RENDER_TARGET_FORMATS = 22,
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL_FORMAT = 23,
    D3D12_STATE_SUBOBJECT_TYPE_SAMPLE_DESC = 24,
    D3D12_STATE_SUBOBJECT_TYPE_FLAGS = 26,
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL1 = 27,
    D3D12_STATE_SUBOBJECT_TYPE_VIEW_INSTANCING = 28,
    D3D12_STATE_SUBOBJECT_TYPE_GENERIC_PROGRAM = 29,
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL2 = 30,
    D3D12_STATE_SUBOBJECT_TYPE_MAX_VALID = (D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL2 + 1),
}
