#include <Windows.h>
#include <D3DCommon.h>
#include <d3d9types.h>
#include <d3d9.h>
#include <dxva9typ.h>
#include <dxva2api.h>
#include <dxva.h>
#include <dxvahd.h>
#include <dxva2swdev.h>
#include <evntrace.h>
#include <dxva2trace.h>