#include <windows.h>
#include <windowsx.h>
#include <evntrace.h>
#include <d3d9.h>
#include <d3d9types.h>
#include <dxva9typ.h>
#include <dxvahd.h>
#include <dxva.h>
#include <dxva2api.h>
#include <dxva2swdev.h>
#include <dxva2trace.h>