// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// Ported from SDL.h and corresponding dependencies of SDL3.
// Original source is Copyright (C) 1997-2024 Sam Lantinga. Licensed under the zlib license.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Silk.NET.SDL;

[NativeTypeName("unsigned int")]
public enum EventType : uint
{
    First = 0,
    Quit = 0x100,
    Terminating,
    LowMemory,
    WillEnterBackground,
    DidEnterBackground,
    WillEnterForeground,
    DidEnterForeground,
    LocaleChanged,
    SystemThemeChanged,
    DisplayOrientation = 0x151,
    DisplayAdded,
    DisplayRemoved,
    DisplayMoved,
    DisplayDesktopModeChanged,
    DisplayCurrentModeChanged,
    DisplayContentScaleChanged,
    DisplayFirst = DisplayOrientation,
    DisplayLast = DisplayContentScaleChanged,
    WindowShown = 0x202,
    WindowHidden,
    WindowExposed,
    WindowMoved,
    WindowResized,
    WindowPixelSizeChanged,
    WindowMetalViewResized,
    WindowMinimized,
    WindowMaximized,
    WindowRestored,
    WindowMouseEnter,
    WindowMouseLeave,
    WindowFocusGained,
    WindowFocusLost,
    WindowCloseRequested,
    WindowHitTest,
    WindowIccprofChanged,
    WindowDisplayChanged,
    WindowDisplayScaleChanged,
    WindowSafeAreaChanged,
    WindowOccluded,
    WindowEnterFullscreen,
    WindowLeaveFullscreen,
    WindowDestroyed,
    WindowHdrStateChanged,
    WindowFirst = WindowShown,
    WindowLast = WindowHdrStateChanged,
    KeyDown = 0x300,
    KeyUp,
    TextEditing,
    TextInput,
    KeymapChanged,
    KeyboardAdded,
    KeyboardRemoved,
    TextEditingCandidates,
    MouseMotion = 0x400,
    MouseButtonDown,
    MouseButtonUp,
    MouseWheel,
    MouseAdded,
    MouseRemoved,
    JoystickAxisMotion = 0x600,
    JoystickBallMotion,
    JoystickHatMotion,
    JoystickButtonDown,
    JoystickButtonUp,
    JoystickAdded,
    JoystickRemoved,
    JoystickBatteryUpdated,
    JoystickUpdateComplete,
    GamepadAxisMotion = 0x650,
    GamepadButtonDown,
    GamepadButtonUp,
    GamepadAdded,
    GamepadRemoved,
    GamepadRemapped,
    GamepadTouchpadDown,
    GamepadTouchpadMotion,
    GamepadTouchpadUp,
    GamepadSensorUpdate,
    GamepadUpdateComplete,
    GamepadSteamHandleUpdated,
    FingerDown = 0x700,
    FingerUp,
    FingerMotion,
    FingerCanceled,
    ClipboardUpdate = 0x900,
    DropFile = 0x1000,
    DropText,
    DropBegin,
    DropComplete,
    DropPosition,
    AudioDeviceAdded = 0x1100,
    AudioDeviceRemoved,
    AudioDeviceFormatChanged,
    SensorUpdate = 0x1200,
    PenProximityIn = 0x1300,
    PenProximityOut,
    PenDown,
    PenUp,
    PenButtonDown,
    PenButtonUp,
    PenMotion,
    PenAxis,
    CameraDeviceAdded = 0x1400,
    CameraDeviceRemoved,
    CameraDeviceApproved,
    CameraDeviceDenied,
    RenderTargetsReset = 0x2000,
    RenderDeviceReset,
    RenderDeviceLost,
    Private0 = 0x4000,
    Private1,
    Private2,
    Private3,
    PollSentinel = 0x7F00,
    User = 0x8000,
    Last = 0xFFFF,
    EnumPadding = 0x7FFFFFFF,
}
