import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docsSidebar: [
        "index",
        {
            type: 'category',
            label: 'OpenGL Documentation',
            link: {
                type: "generated-index",
                slug: "/opengl"
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'opengl/c1'
                },
            ],
        },
        {
            type: 'category',
            label: 'Vulkan Documentation',
            link: {
                type: "generated-index",
                slug: "/vulkan"
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'vulkan'
                },
            ],
        },
        {
            type: 'category',
            label: 'High Level Utilities',
            link: {
                type: "generated-index",
                slug: "/hlu"
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'hlu'
                },
            ],
        },
        {
            type: 'category',
            label: 'Miscellaneous',
            link: {
                type: 'generated-index',
                title: 'Miscellaneous',
                description: 'This section of the website contains useful miscellaneous tidbits which we think will come in handy to get the most out of your Silk.NET application! It also contains other more general information pertaining to the project.',
                slug: "/silk.net"
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'silk.net'
                }
            ],
        },
    ],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
