// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from winrt/windows.web.http.h in the Windows SDK for Windows 10.0.26100.0
// Original source is Copyright © Microsoft. All rights reserved.
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.WinRT;

public enum HttpStatusCode
{
    HttpStatusCode_None = 0,
    HttpStatusCode_Continue = 100,
    HttpStatusCode_SwitchingProtocols = 101,
    HttpStatusCode_Processing = 102,
    HttpStatusCode_Ok = 200,
    HttpStatusCode_Created = 201,
    HttpStatusCode_Accepted = 202,
    HttpStatusCode_NonAuthoritativeInformation = 203,
    HttpStatusCode_NoContent = 204,
    HttpStatusCode_ResetContent = 205,
    HttpStatusCode_PartialContent = 206,
    HttpStatusCode_MultiStatus = 207,
    HttpStatusCode_AlreadyReported = 208,
    HttpStatusCode_IMUsed = 226,
    HttpStatusCode_MultipleChoices = 300,
    HttpStatusCode_MovedPermanently = 301,
    HttpStatusCode_Found = 302,
    HttpStatusCode_SeeOther = 303,
    HttpStatusCode_NotModified = 304,
    HttpStatusCode_UseProxy = 305,
    HttpStatusCode_TemporaryRedirect = 307,
    HttpStatusCode_PermanentRedirect = 308,
    HttpStatusCode_BadRequest = 400,
    HttpStatusCode_Unauthorized = 401,
    HttpStatusCode_PaymentRequired = 402,
    HttpStatusCode_Forbidden = 403,
    HttpStatusCode_NotFound = 404,
    HttpStatusCode_MethodNotAllowed = 405,
    HttpStatusCode_NotAcceptable = 406,
    HttpStatusCode_ProxyAuthenticationRequired = 407,
    HttpStatusCode_RequestTimeout = 408,
    HttpStatusCode_Conflict = 409,
    HttpStatusCode_Gone = 410,
    HttpStatusCode_LengthRequired = 411,
    HttpStatusCode_PreconditionFailed = 412,
    HttpStatusCode_RequestEntityTooLarge = 413,
    HttpStatusCode_RequestUriTooLong = 414,
    HttpStatusCode_UnsupportedMediaType = 415,
    HttpStatusCode_RequestedRangeNotSatisfiable = 416,
    HttpStatusCode_ExpectationFailed = 417,
    HttpStatusCode_UnprocessableEntity = 422,
    HttpStatusCode_Locked = 423,
    HttpStatusCode_FailedDependency = 424,
    HttpStatusCode_UpgradeRequired = 426,
    HttpStatusCode_PreconditionRequired = 428,
    HttpStatusCode_TooManyRequests = 429,
    HttpStatusCode_RequestHeaderFieldsTooLarge = 431,
    HttpStatusCode_InternalServerError = 500,
    HttpStatusCode_NotImplemented = 501,
    HttpStatusCode_BadGateway = 502,
    HttpStatusCode_ServiceUnavailable = 503,
    HttpStatusCode_GatewayTimeout = 504,
    HttpStatusCode_HttpVersionNotSupported = 505,
    HttpStatusCode_VariantAlsoNegotiates = 506,
    HttpStatusCode_InsufficientStorage = 507,
    HttpStatusCode_LoopDetected = 508,
    HttpStatusCode_NotExtended = 510,
    HttpStatusCode_NetworkAuthenticationRequired = 511,
}
