name: CI Build
on:
  push:
    branches:
      - 'main'
      - 'release/**'
    paths-ignore:
      - 'documentation/**'
    tags:
      - '*'
  pull_request: # all branches
permissions:
  packages: write
jobs:
  Build:
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3.5.2
      with:
        submodules: 'false'
    - name: Clone submodules non-recursively
      run: git submodule update --init --depth 0
    - name: Setup Java JDK 21
      uses: actions/setup-java@v2.3.0
      with:
        java-version: 21
        distribution: "temurin"
    - name: Setup Android Environment
      uses: android-actions/setup-android@v2
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
    - name: Install Android Platforms
      run: |
        sdkmanager --install "build-tools;32.0.0"
        sdkmanager --install "platform-tools"
        sdkmanager --install "platforms;android-31"
        sdkmanager --install "platforms;android-33"
        sdkmanager --install "platforms;android-34"
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.414
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.102
    - name: Install Workloads
      run: dotnet workload install android ios maccatalyst
    - name: Validation Checks
      if: ${{ github.repository != 'dotnet/Silk.NET' || !startsWith(github.ref, 'refs/tags/') }}
      run: ./build.sh ValidateSolution
    - name: Compile
      if: ${{ github.repository != 'dotnet/Silk.NET' || !startsWith(github.ref, 'refs/tags/') }}
      run: ./build.sh Compile
    - name: Test
      if: ${{ github.repository != 'dotnet/Silk.NET' || !startsWith(github.ref, 'refs/tags/') }}
      run: ./build.sh Test
