name: Shaderc
on:
  push:
    branches-ignore:
      - "ci/**"
      - "develop/**"
      - "main"
    paths:
      - build/submodules/shaderc
      - build/nuke/Native/Core.cs
      - build/nuke/Native/Shaderc.cs
      - .github/workflows/shaderc.yml
jobs:
  Build:
    if: github.repository == 'dotnet/Silk.NET'
    strategy:
      fail-fast: false
      matrix:
        env:
          - os: windows-2022
            name: Windows
            nuke_invoke: ./build.cmd
            extras: ""
    name: ${{ matrix.env.name }} Build
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
      - name: Checkout submodules, configure git
        run: |
          git submodule update --init --recursive --depth 0 build/submodules/shaderc
          git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
          git config --local user.name "The Silk.NET Automaton"
      - name: Extra prerequisites
        run: |
          echo running extras
          ${{ matrix.env.extras }}
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Setup .NET 6.0 and .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.201
            7.0.*
            8.0.*
      - name: Build Shaderc
        run: ${{ matrix.env.nuke_invoke }} Shaderc
        env:
          PUSHABLE_GITHUB_TOKEN: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}

