#include <Windows.h>
#include <rpcdcep.h>
#include <WTypesbase.h>
#include <Documenttarget.h>
#include <evntprov.h>
#include <evntrace.h>
#include <minwinbase.h>
#include <timezoneapi.h>
#include <winnt.h>
#include <handleapi.h>
#include <fileapi.h>
#include <objidlbase.h>
#include <objidl.h>
